// AUTO-GENERATED by generate-app-manifest.ts - DO NOT EDIT
// Generated: 2025-12-28T16:49:40.485Z
// Apps: 53

import type { App } from '../core/src/app';

/** Platform types for targeting specific form factors */
export type Platform = 'phone' | 'tablet' | 'desktop';

/** Static app definition with all metadata */
export interface GeneratedAppDefinition {
  /** Display name for the app */
  name: string;
  /** The builder function (pre-imported) */
  builder: (...args: any[]) => void | Promise<void>;
  /** SVG icon content or theme icon name */
  icon: string;
  /** App category for grouping */
  category?: string;
  /** Builder function arguments in order */
  args: string[];
  /** Instance count: 'one' (default), 'many', or 'desktop-many' */
  count: 'one' | 'many' | 'desktop-many';
  /** Supported platforms */
  platforms: Platform[];
}

// App builder imports
import { create3DCubeApp as app3dCubeBuilder } from '../ported-apps/3d-cube/3d-cube';
import { createAlarmsApp as alarmsBuilder } from './alarms/alarms';
import { buildAnimationDemo as animationDemoBuilder } from '../examples/animation-demo';
import { createAudioRecorderApp as audioRecorderBuilder } from './audio-recorder/audio-recorder';
import { createBoingApp as boingBuilder } from '../ported-apps/boing/boing';
import { createBurningShipApp as burningShipBuilder } from './burning-ship/burning-ship';
import { buildCalculator as calculatorBuilder } from '../examples/calculator';
import { createCalendarApp as calendarBuilder } from './calendar/calendar';
import { createCameraApp as cameraBuilder } from './camera/camera';
import { createChessApp as chessBuilder } from '../ported-apps/chess/chess';
import { createClockApp as clockBuilder } from './clock/clock';
import { createContactsApp as contactsBuilder } from './contacts/contacts';
import { buildCounter as counterBuilder } from '../examples/02-counter';
import { buildDailyChecklist as dailyChecklistBuilder } from '../examples/daily-checklist';
import { buildDailyChecklistMVC as dailyChecklistMvcBuilder } from '../examples/daily-checklist-mvc';
import { buildDiceRoller as diceRollerBuilder } from '../examples/18-dice-roller';
import { buildDiskTreeApp as diskTreeBuilder } from './disk-tree';
import { buildEdlinApp as edlinBuilder } from '../ported-apps/edlin/edlin';
import { buildElegantDemo as elegantAnimationsBuilder } from '../examples/animation-elegant';
import { createElizaApp as elizaBuilder } from './eliza/eliza';
import { createEyesApp as eyesBuilder } from './eyes/eyes';
import { createFallingBlocksApp as fallingBlocksBuilder } from '../ported-apps/falling-blocks/falling-blocks';
import { createFallingLettersApp as fallingLettersBuilder } from '../ported-apps/falling-letters/falling-letters';
import { createFylesApp as fileBrowserBuilder } from '../ported-apps/fyles/fyles';
import { buildFullCalculator as fullCalculatorBuilder } from '../examples/full-calculator';
import { createGameOfLifeApp as gameOfLifeBuilder } from '../ported-apps/game-of-life/game-of-life';
import { createHexViewApp as hexviewBuilder } from './hexview/hexview';
import { buildImageResizerApp as imageResizerBuilder } from './image-resizer';
import { createImageViewerApp as imageViewerBuilder } from '../ported-apps/image-viewer/image-viewer';
import { createJuliaSetApp as juliaSetBuilder } from './julia-set/julia-set';
import { createMahjonggApp as mahjonggBuilder } from '../ported-apps/mahjongg/mahjongg';
import { createMandelbrotApp as mandelbrotBuilder } from './mandelbrot/mandelbrot';
import { createMessagesApp as messagesBuilder } from './messages';
import { createMinefieldApp as minefieldBuilder } from './minefield/minefield';
import { createMusicPlayerApp as musicPlayerBuilder } from './music-player/music-player';
import { createNewtonFractalApp as newtonFractalBuilder } from './newton-fractal/newton-fractal';
import { buildPasswordGenerator as passwordGeneratorBuilder } from '../examples/16-password-generator';
import { createDialerApp as phoneBuilder } from './dialer/dialer';
import { createPixelEditorApp as pixelEditorBuilder } from '../ported-apps/pixeledit/pixeledit';
import { buildPomodoroApp as pomodoroBuilder } from './pomodoro';
import { createPowerMenuApp as powerBuilder } from './power-menu';
import { createPrimeGridAppStandalone as primeGridVisualizerBuilder } from '../ported-apps/prime-grid-visualizer/prime-grid-visualizer';
import { buildQuizApp as quizAppBuilder } from '../examples/21-quiz-app';
import { buildRockPaperScissors as rockPaperScissorsBuilder } from '../examples/20-rock-paper-scissors';
import { createSettingsApp as settingsBuilder } from './settings';
import { createSlydesApp as slydesBuilder } from '../ported-apps/slydes/slydes';
import { createStopwatchApp as stopwatchBuilder } from './stopwatch/stopwatch';
import { createSudokuApp as sudokuBuilder } from '../ported-apps/sudoku/sudoku';
import { createTimerApp as timerBuilder } from './timer/timer';
import { buildTipCalculator as tipCalculatorBuilder } from '../examples/15-tip-calculator';
import { createTodoApp as todomvcBuilder } from '../examples/todomvc';
import { createTricornApp as tricornBuilder } from './tricorn/tricorn';
import { createWeatherApp as weatherBuilder } from './weather/weather';

/**
 * All discovered apps with metadata
 */
export const allApps: GeneratedAppDefinition[] = [
  {
    name: '3D Cube',
    builder: app3dCubeBuilder,
    icon: `<svg viewBox="0 0 24 24">
<polygon points="2,7 2,17 12,22 12,12" fill="#228B22" stroke="#333" stroke-width="1"/>
<polygon points="22,7 12,12 12,22 22,17" fill="#DC143C" stroke="#333" stroke-width="1"/>
<polygon points="12,2 2,7 12,12 22,7" fill="#FFD700" stroke="#333" stroke-width="1"/>
</svg>`,
    category: 'games',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Alarms',
    builder: alarmsBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor">
<circle cx="12" cy="13" r="8" fill="none" stroke="currentColor" stroke-width="2"/>
<path d="M12 9v4l2 2" fill="none" stroke="currentColor" stroke-width="2"/>
<path d="M5 3L2 6" stroke="currentColor" stroke-width="2"/>
<path d="M19 3l3 3" stroke="currentColor" stroke-width="2"/>
</svg>`,
    category: 'utilities',
    args: ['app', 'clock', 'notifications', 'lifecycle'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Animation Demo',
    builder: animationDemoBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14"/><path d="M12 5l7 7-7 7"/><circle cx="5" cy="12" r="2" fill="currentColor"/></svg>`,
    category: undefined,
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Audio Recorder',
    builder: audioRecorderBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 14c1.66 0 3-1.34 3-3V5c0-1.66-1.34-3-3-3s-3 1.34-3 3v6c0 1.66 1.34 3 3 3z"/><path d="M17 16.91c-1.48 1.46-3.51 2.36-5.77 2.36-2.26 0-4.29-.9-5.77-2.36M19 12h2c0 .91-.24 1.75-.67 2.5M5 12H3c0-.91.24-1.75.67-2.5"/></svg>`,
    category: 'media',
    args: ['app', 'recording'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Boing',
    builder: boingBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10" fill="#CC0000" stroke="#FFFFFF"/><path d="M7 7L17 17M7 17L17 7M12 2v20M2 12h20" stroke="#FFFFFF" stroke-width="1.5"/></svg>`,
    category: 'games',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Burning Ship',
    builder: burningShipBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M20 21c-1.39 0-2.78-.47-4-1.32-2.44 1.71-5.56 1.71-8 0C6.78 20.53 5.39 21 4 21H2v2h2c1.38 0 2.74-.35 4-.99 2.52 1.29 5.48 1.29 8 0 1.26.65 2.62.99 4 .99h2v-2h-2zM3.95 19H4c1.6 0 3.02-.88 4-2 .98 1.12 2.4 2 4 2s3.02-.88 4-2c.98 1.12 2.4 2 4 2h.05l1.89-6.68c.08-.26.06-.54-.06-.78s-.34-.42-.6-.5L20 10.62V6c0-1.1-.9-2-2-2h-3V1H9v3H6c-1.1 0-2 .9-2 2v4.62l-1.29.42c-.26.08-.48.26-.6.5s-.15.52-.06.78L3.95 19z"/></svg>`,
    category: 'graphics',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Calculator',
    builder: calculatorBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor"><rect x="4" y="2" width="16" height="20" rx="2" fill="none" stroke="currentColor" stroke-width="2"/><line x1="8" y1="7" x2="16" y2="7" stroke="currentColor" stroke-width="2"/><circle cx="8" cy="12" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="16" cy="12" r="1.5"/><circle cx="8" cy="16" r="1.5"/><circle cx="12" cy="16" r="1.5"/><circle cx="16" cy="16" r="1.5"/></svg>`,
    category: 'utilities',
    args: ['app'],
    count: 'desktop-many',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Calendar',
    builder: calendarBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M19 3h-1V1h-2v2H8V1H6v2H5c-1.11 0-1.99.9-1.99 2L3 19c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 16H5V8h14v11z"/></svg>`,
    category: 'utilities',
    args: ['app', 'calendar'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Camera',
    builder: cameraBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M21 19V5c0-1.1-.9-2-2-2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2zM8.5 13.5l2.5 3.01L14.5 12l4.5 6H5l3.5-4.5z"/></svg>`,
    category: 'media',
    args: ['app', 'camera'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Chess',
    builder: chessBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="#333333"><path d="M19 22H5v-2h14v2zm-3-4H8l-1-4 2-1v-2c0-1 1-3 2-4l-1-2 1-1 1 1c1-1 2-1 3 0l1-1 1 1-1 2c1 1 2 3 2 4v2l2 1-1 4z"/></svg>`,
    category: 'games',
    args: ['app', 'resources'],
    count: 'many',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Clock',
    builder: clockBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor"><circle cx="12" cy="12" r="10" fill="none" stroke="currentColor" stroke-width="2"/>
<polyline points="12 6 12 12 18 12" fill="none" stroke="currentColor" stroke-width="2"/>
</svg>`,
    category: 'utilities',
    args: ['app', 'clock', 'notifications', 'lifecycle'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Contacts',
    builder: contactsBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/></svg>`,
    category: 'phone',
    args: ['app', 'contacts'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Counter',
    builder: counterBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="4" y="4" width="16" height="16" rx="2"/><path d="M12 8v8"/><path d="M8 12h8"/></svg>`,
    category: 'utilities',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Daily Checklist',
    builder: dailyChecklistBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
<path d="M9 11l3 3L22 4"/>
<path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11"/>
</svg>`,
    category: 'productivity',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Daily Checklist MVC',
    builder: dailyChecklistMvcBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
<path d="M9 11l3 3L22 4"/>
<path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11"/>
</svg>`,
    category: 'productivity',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Dice Roller',
    builder: diceRollerBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="2" width="20" height="20" rx="3"/><circle cx="8" cy="8" r="1.5" fill="currentColor"/><circle cx="16" cy="8" r="1.5" fill="currentColor"/><circle cx="12" cy="12" r="1.5" fill="currentColor"/><circle cx="8" cy="16" r="1.5" fill="currentColor"/><circle cx="16" cy="16" r="1.5" fill="currentColor"/></svg>`,
    category: 'games',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Disk Tree',
    builder: diskTreeBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M21 21H3V3h8V1H3a2 2 0 0 0-2 2v18a2 2 0 0 0 2 2h18a2 2 0 0 0 2-2v-8h-2z"/><path d="M11 8h10V6H11z"/><path d="M11 13h10v-2H11z"/><path d="M11 18h10v-2H11z"/></svg>`,
    category: 'utilities',
    args: ['app', 'win'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Edlin',
    builder: edlinBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><line x1="10" y1="9" x2="8" y2="9"/></svg>`,
    category: 'utilities',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Elegant Animations',
    builder: elegantAnimationsBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="3"/><path d="M12 2v4m0 12v4M2 12h4m12 0h4"/><path d="M4.93 4.93l2.83 2.83m8.48 8.48l2.83 2.83M4.93 19.07l2.83-2.83m8.48-8.48l2.83-2.83"/></svg>`,
    category: undefined,
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'ELIZA',
    builder: elizaBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M20 2H4c-1.1 0-2 .9-2 2v18l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm0 14H6l-2 2V4h16v12z"/><circle cx="8" cy="10" r="1.5"/><circle cx="12" cy="10" r="1.5"/><circle cx="16" cy="10" r="1.5"/></svg>`,
    category: 'utilities',
    args: ['app'],
    count: 'many',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Eyes',
    builder: eyesBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="8" cy="12" r="4"/><circle cx="16" cy="12" r="4"/><circle cx="8" cy="12" r="1.5" fill="currentColor"/><circle cx="16" cy="12" r="1.5" fill="currentColor"/></svg>`,
    category: 'fun',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Falling Blocks',
    builder: fallingBlocksBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1">
<rect x="2" y="14" width="4" height="4" fill="#FF6B6B" stroke="#333"/>
<rect x="6" y="14" width="4" height="4" fill="#FF6B6B" stroke="#333"/>
<rect x="6" y="18" width="4" height="4" fill="#FF6B6B" stroke="#333"/>
<rect x="10" y="18" width="4" height="4" fill="#FF6B6B" stroke="#333"/>
<rect x="14" y="18" width="4" height="4" fill="#4ECDC4" stroke="#333"/>
<rect x="18" y="18" width="4" height="4" fill="#FFE66D" stroke="#333"/>
<rect x="10" y="6" width="4" height="4" fill="#4ECDC4" stroke="#333"/>
<rect x="10" y="10" width="4" height="4" fill="#4ECDC4" stroke="#333"/>
</svg>`,
    category: 'games',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Falling Letters',
    builder: fallingLettersBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
<rect x="2" y="2" width="5" height="20" fill="#1a5276" stroke="#333"/>
<rect x="9" y="6" width="5" height="16" fill="#2874a6" stroke="#333"/>
<rect x="16" y="4" width="5" height="18" fill="#3498db" stroke="#333"/>
<text x="3" y="8" font-size="4" fill="white" font-weight="bold">A</text>
<text x="10" y="12" font-size="4" fill="white" font-weight="bold">B</text>
<text x="17" y="10" font-size="4" fill="white" font-weight="bold">C</text>
</svg>`,
    category: 'games',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'File Browser',
    builder: fileBrowserBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 19a2 2 0 01-2 2H4a2 2 0 01-2-2V5a2 2 0 012-2h5l2 3h9a2 2 0 012 2v11z"/></svg>`,
    category: 'utilities',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Full Calculator',
    builder: fullCalculatorBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor">
<rect x="3" y="1" width="18" height="22" rx="2" fill="none" stroke="currentColor" stroke-width="2"/>
<rect x="5" y="3" width="14" height="4" fill="currentColor" opacity="0.3"/>
<circle cx="7" cy="10" r="1.2"/><circle cx="12" cy="10" r="1.2"/><circle cx="17" cy="10" r="1.2"/>
<circle cx="7" cy="14" r="1.2"/><circle cx="12" cy="14" r="1.2"/><circle cx="17" cy="14" r="1.2"/>
<circle cx="7" cy="18" r="1.2"/><circle cx="12" cy="18" r="1.2"/><circle cx="17" cy="18" r="1.2"/>
</svg>`,
    category: 'utilities',
    args: ['app'],
    count: 'desktop-many',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Game of Life',
    builder: gameOfLifeBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="6" height="6" fill="currentColor"/><rect x="9" y="9" width="6" height="6" fill="currentColor"/><rect x="15" y="3" width="6" height="6"/><rect x="3" y="15" width="6" height="6"/><rect x="15" y="15" width="6" height="6" fill="currentColor"/></svg>`,
    category: 'games',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'HexView',
    builder: hexviewBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M9 8h.01M15 8h.01M9 12h.01M15 12h.01M9 16h.01M15 16h.01"/></svg>`,
    category: 'utilities',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Image Resizer',
    builder: imageResizerBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor"><rect x="3" y="3" width="18" height="18" rx="1" stroke="currentColor" stroke-width="2" fill="none"/><circle cx="8" cy="8" r="1.5" fill="currentColor"/><path d="M21 12L15 6M3 21l6-6" stroke="currentColor" stroke-width="1.5" fill="none"/></svg>`,
    category: 'utilities',
    args: ['app', 'win'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Image Viewer',
    builder: imageViewerBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="M21 15l-5-5L5 21"/></svg>`,
    category: 'graphics',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Julia Set',
    builder: juliaSetBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8z"/><circle cx="8" cy="12" r="2"/><circle cx="16" cy="12" r="2"/></svg>`,
    category: 'graphics',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Mahjongg',
    builder: mahjonggBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
<rect x="2" y="4" width="8" height="10" rx="1" fill="#f5deb3" stroke="#8B4513"/>
<rect x="6" y="2" width="8" height="10" rx="1" fill="#ffe4c4" stroke="#8B4513"/>
<rect x="10" y="6" width="8" height="10" rx="1" fill="#faebd7" stroke="#8B4513"/>
<text x="10" y="13" font-size="6" fill="#8B4513">M</text>
</svg>`,
    category: 'games',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Mandelbrot',
    builder: mandelbrotBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor"><circle cx="12" cy="8" r="6" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="8" cy="14" r="3" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="16" cy="14" r="3" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="18" r="2" fill="none" stroke="currentColor" stroke-width="2"/></svg>`,
    category: 'graphics',
    args: ['app'],
    count: 'many',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Messages',
    builder: messagesBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M20 2H4c-1.1 0-2 .9-2 2v18l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm0 14H6l-2 2V4h16v12z"/><path d="M7 9h10v2H7zm0-3h10v2H7z"/></svg>`,
    category: 'phone',
    args: ['app', 'sms', 'contacts'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Minefield',
    builder: minefieldBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="3" fill="currentColor"/><path d="M12 2v4M12 18v4M2 12h4M18 12h4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83"/></svg>`,
    category: 'games',
    args: ['app'],
    count: 'many',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Music Player',
    builder: musicPlayerBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 3v9.28c-.47-.46-1.12-.75-1.84-.75-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3V7h4V3h-5zm8-2H4c-1.1 0-2 .9-2 2v16c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V3c0-1.1-.9-2-2-2z"/></svg>`,
    category: 'media',
    args: ['app', 'music'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Newton Fractal',
    builder: newtonFractalBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M19.07 4.93l-1.41 1.41A8.014 8.014 0 0 1 20 12c0 4.42-3.58 8-8 8s-8-3.58-8-8c0-4.08 3.05-7.44 7-7.93v2.02C8.16 6.57 6 9.03 6 12c0 3.31 2.69 6 6 6s6-2.69 6-6c0-1.66-.67-3.16-1.76-4.24l-1.41 1.41C15.55 9.9 16 10.9 16 12c0 2.21-1.79 4-4 4s-4-1.79-4-4c0-1.86 1.28-3.41 3-3.86v2.14c-.6.35-1 .98-1 1.72 0 1.1.9 2 2 2s2-.9 2-2c0-.74-.4-1.38-1-1.72V2h-1C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10c0-2.76-1.12-5.26-2.93-7.07z"/></svg>`,
    category: 'graphics',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Password Generator',
    builder: passwordGeneratorBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0110 0v4"/><circle cx="12" cy="16" r="1"/></svg>`,
    category: 'utilities',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Phone',
    builder: phoneBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M6.62 10.79c1.44 2.83 3.76 5.14 6.59 6.59l2.2-2.2c.27-.27.67-.36 1.02-.24 1.12.37 2.33.57 3.57.57.55 0 1 .45 1 1V20c0 .55-.45 1-1 1-9.39 0-17-7.61-17-17 0-.55.45-1 1-1h3.5c.55 0 1 .45 1 1 0 1.25.2 2.45.57 3.57.11.35.03.74-.25 1.02l-2.2 2.2z"/></svg>`,
    category: 'phone',
    args: ['app', 'modem', 'contacts'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Pixel Editor',
    builder: pixelEditorBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="4" y="4" width="4" height="4" fill="currentColor"/><rect x="8" y="8" width="4" height="4" fill="currentColor"/><rect x="12" y="12" width="4" height="4" fill="currentColor"/><rect x="16" y="4" width="4" height="4"/><rect x="4" y="16" width="4" height="4"/><path d="M2 2h20v20H2z"/></svg>`,
    category: 'graphics',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Pomodoro',
    builder: pomodoroBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor"><circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="2" fill="none"/><path d="M12 6v6l4.5 2.5" stroke="currentColor" stroke-width="2" fill="none"/></svg>`,
    category: 'utilities',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Power',
    builder: powerBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M13 3h-2v10h2V3zm4.83 2.17l-1.42 1.42C17.99 7.86 19 9.81 19 12c0 3.87-3.13 7-7 7s-7-3.13-7-7c0-2.19 1.01-4.14 2.58-5.42L6.17 5.17C4.23 6.82 3 9.26 3 12c0 4.97 4.03 9 9 9s9-4.03 9-9c0-2.74-1.23-5.18-3.17-6.83z"/></svg>`,
    category: 'system',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet'],
  },
  {
    name: 'Prime Grid Visualizer',
    builder: primeGridVisualizerBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="2" width="20" height="20" rx="1"/><line x1="6" y1="6" x2="6" y2="18"/><line x1="10" y1="6" x2="10" y2="18"/><line x1="14" y1="6" x2="14" y2="18"/><line x1="18" y1="6" x2="18" y2="18"/><line x1="2" y1="6" x2="22" y2="6"/><line x1="2" y1="10" x2="22" y2="10"/><line x1="2" y1="14" x2="22" y2="14"/><line x1="2" y1="18" x2="22" y2="18"/></svg>`,
    category: 'utilities',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Quiz App',
    builder: quizAppBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M9.09 9a3 3 0 015.83 1c0 2-3 3-3 3"/><path d="M12 17h.01"/></svg>`,
    category: 'games',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Rock Paper Scissors',
    builder: rockPaperScissorsBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 11V6a2 2 0 10-4 0v5"/><path d="M14 10V4a2 2 0 10-4 0v6"/><path d="M10 10.5V6a2 2 0 10-4 0v8"/><path d="M18 8a2 2 0 114 0v6a8 8 0 01-8 8h-2a8 8 0 01-8-8V9a2 2 0 114 0"/></svg>`,
    category: 'games',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Settings',
    builder: settingsBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z" fill="none" stroke="currentColor" stroke-width="2"/></svg>`,
    category: 'system',
    args: ['app', 'settings'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Slydes',
    builder: slydesBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="4" width="20" height="14" rx="2"/><path d="M12 18v4"/><path d="M8 22h8"/><path d="M7 8h10"/><path d="M7 12h6"/></svg>`,
    category: 'productivity',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Stopwatch',
    builder: stopwatchBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor">
<circle cx="12" cy="13" r="8" fill="none" stroke="currentColor" stroke-width="2"/>
<path d="M12 9v5" stroke="currentColor" stroke-width="2"/>
<path d="M10 2h4" stroke="currentColor" stroke-width="2"/>
<path d="M18 5l2 2" stroke="currentColor" stroke-width="2"/>
</svg>`,
    category: 'utilities',
    args: ['app', 'clock', 'notifications', 'lifecycle'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Sudoku',
    builder: sudokuBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
<rect x="2" y="2" width="20" height="20" rx="1" stroke="#333"/>
<line x1="8" y1="2" x2="8" y2="22" stroke="#333"/>
<line x1="16" y1="2" x2="16" y2="22" stroke="#333"/>
<line x1="2" y1="8" x2="22" y2="8" stroke="#333"/>
<line x1="2" y1="16" x2="22" y2="16" stroke="#333"/>
<text x="5" y="7" font-size="4" fill="#00008B">5</text>
<text x="11" y="14" font-size="4" fill="#00008B">7</text>
<text x="17" y="21" font-size="4" fill="#00008B">3</text>
</svg>`,
    category: 'games',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Timer',
    builder: timerBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor">
<circle cx="12" cy="13" r="8" fill="none" stroke="currentColor" stroke-width="2"/>
<path d="M12 9v4" stroke="currentColor" stroke-width="2"/>
<path d="M10 2h4" stroke="currentColor" stroke-width="2"/>
</svg>`,
    category: 'utilities',
    args: ['app', 'clock', 'notifications', 'lifecycle'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Tip Calculator',
    builder: tipCalculatorBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="4" width="20" height="16" rx="2"/><path d="M12 12a3 3 0 100-6 3 3 0 000 6z"/><path d="M6 16h.01"/><path d="M18 16h.01"/><path d="M12 16v2"/></svg>`,
    category: 'utilities',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'TodoMVC',
    builder: todomvcBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11"/></svg>`,
    category: 'productivity',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Tricorn',
    builder: tricornBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 2L4.5 20.29l.71.71L12 18l6.79 3 .71-.71z"/></svg>`,
    category: 'graphics',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  },
  {
    name: 'Weather',
    builder: weatherBuilder,
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="M4.93 4.93l1.41 1.41"/><path d="M17.66 17.66l1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="M6.34 17.66l-1.41 1.41"/><path d="M19.07 4.93l-1.41 1.41"/></svg>`,
    category: 'utilities',
    args: ['app'],
    count: 'one',
    platforms: ['phone', 'tablet', 'desktop'],
  }
];

/**
 * Builder functions by identifier (for lookup)
 */
export const appBuilders: Record<string, (...args: any[]) => void | Promise<void>> = {
  'app3dCube': app3dCubeBuilder,
  'alarms': alarmsBuilder,
  'animationDemo': animationDemoBuilder,
  'audioRecorder': audioRecorderBuilder,
  'boing': boingBuilder,
  'burningShip': burningShipBuilder,
  'calculator': calculatorBuilder,
  'calendar': calendarBuilder,
  'camera': cameraBuilder,
  'chess': chessBuilder,
  'clock': clockBuilder,
  'contacts': contactsBuilder,
  'counter': counterBuilder,
  'dailyChecklist': dailyChecklistBuilder,
  'dailyChecklistMvc': dailyChecklistMvcBuilder,
  'diceRoller': diceRollerBuilder,
  'diskTree': diskTreeBuilder,
  'edlin': edlinBuilder,
  'elegantAnimations': elegantAnimationsBuilder,
  'eliza': elizaBuilder,
  'eyes': eyesBuilder,
  'fallingBlocks': fallingBlocksBuilder,
  'fallingLetters': fallingLettersBuilder,
  'fileBrowser': fileBrowserBuilder,
  'fullCalculator': fullCalculatorBuilder,
  'gameOfLife': gameOfLifeBuilder,
  'hexview': hexviewBuilder,
  'imageResizer': imageResizerBuilder,
  'imageViewer': imageViewerBuilder,
  'juliaSet': juliaSetBuilder,
  'mahjongg': mahjonggBuilder,
  'mandelbrot': mandelbrotBuilder,
  'messages': messagesBuilder,
  'minefield': minefieldBuilder,
  'musicPlayer': musicPlayerBuilder,
  'newtonFractal': newtonFractalBuilder,
  'passwordGenerator': passwordGeneratorBuilder,
  'phone': phoneBuilder,
  'pixelEditor': pixelEditorBuilder,
  'pomodoro': pomodoroBuilder,
  'power': powerBuilder,
  'primeGridVisualizer': primeGridVisualizerBuilder,
  'quizApp': quizAppBuilder,
  'rockPaperScissors': rockPaperScissorsBuilder,
  'settings': settingsBuilder,
  'slydes': slydesBuilder,
  'stopwatch': stopwatchBuilder,
  'sudoku': sudokuBuilder,
  'timer': timerBuilder,
  'tipCalculator': tipCalculatorBuilder,
  'todomvc': todomvcBuilder,
  'tricorn': tricornBuilder,
  'weather': weatherBuilder
};

/**
 * Filter apps by platform
 */
export function getAppsForPlatform(platform: Platform): GeneratedAppDefinition[] {
  return allApps.filter(app => app.platforms.includes(platform));
}

/**
 * Filter apps by category
 */
export function getAppsByCategory(category: string): GeneratedAppDefinition[] {
  return allApps.filter(app => app.category === category);
}

/**
 * Get unique categories
 */
export function getCategories(): string[] {
  const categories = new Set<string>();
  for (const app of allApps) {
    if (app.category) {
      categories.add(app.category);
    }
  }
  return Array.from(categories).sort();
}
