/**
 * Generate CVG drawing functions from card SVG files.
 *
 * Reads all 53 SVGs from faces/, calls cosyne's transpileSvg() on each,
 * and writes solitaire-cards-cvg.ts.
 *
 * Run once, output checked in:
 *   npx ts-node generate-card-functions.ts
 */

import { transpileSvg } from '../../cosyne/src/cvg/transpiler';
import * as fs from 'fs';
import * as path from 'path';

const facesDir = path.join(__dirname, 'faces');
const files = fs.readdirSync(facesDir).filter(f => f.endsWith('.svg')).sort();

let output = `/**
 * Auto-generated CVG drawing functions for solitaire cards.
 * Generated by generate-card-functions.ts — do not edit manually.
 */

import type { CvgContext } from 'cosyne';

export const CARD_VB_WIDTH = 167.087;
export const CARD_VB_HEIGHT = 242.667;

`;

for (const file of files) {
  const svgPath = path.join(facesDir, file);
  const svg = fs.readFileSync(svgPath, 'utf-8');
  const body = transpileSvg(svg);
  const fnName = 'draw_' + file.replace('.svg', '').replace(/[^a-zA-Z0-9]/g, '_');
  output += `export function ${fnName}(s: CvgContext) {\n`;
  // Indent each line of the body
  for (const line of body.split('\n')) {
    if (line.trim()) {
      output += `  ${line}\n`;
    }
  }
  output += `}\n\n`;
}

output += `export const CARD_DRAW_MAP: Record<string, (s: CvgContext) => void> = {\n`;
for (const file of files) {
  const fnName = 'draw_' + file.replace('.svg', '').replace(/[^a-zA-Z0-9]/g, '_');
  output += `  '${file}': ${fnName},\n`;
}
output += `};\n`;

const outPath = path.join(__dirname, 'solitaire-cards-cvg.ts');
fs.writeFileSync(outPath, output);
console.log(`Generated ${files.length} card functions → ${outPath}`);
