// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: bridge.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Text alignment options for labels
type TextAlignment int32

const (
	TextAlignment_TEXT_ALIGN_LEADING  TextAlignment = 0 // Left-aligned (default)
	TextAlignment_TEXT_ALIGN_CENTER   TextAlignment = 1 // Center-aligned
	TextAlignment_TEXT_ALIGN_TRAILING TextAlignment = 2 // Right-aligned
)

// Enum value maps for TextAlignment.
var (
	TextAlignment_name = map[int32]string{
		0: "TEXT_ALIGN_LEADING",
		1: "TEXT_ALIGN_CENTER",
		2: "TEXT_ALIGN_TRAILING",
	}
	TextAlignment_value = map[string]int32{
		"TEXT_ALIGN_LEADING":  0,
		"TEXT_ALIGN_CENTER":   1,
		"TEXT_ALIGN_TRAILING": 2,
	}
)

func (x TextAlignment) Enum() *TextAlignment {
	p := new(TextAlignment)
	*p = x
	return p
}

func (x TextAlignment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextAlignment) Descriptor() protoreflect.EnumDescriptor {
	return file_bridge_proto_enumTypes[0].Descriptor()
}

func (TextAlignment) Type() protoreflect.EnumType {
	return &file_bridge_proto_enumTypes[0]
}

func (x TextAlignment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TextAlignment.Descriptor instead.
func (TextAlignment) EnumDescriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{0}
}

// Text wrapping options for labels
type TextWrapping int32

const (
	TextWrapping_TEXT_WRAP_OFF      TextWrapping = 0 // No wrapping (default)
	TextWrapping_TEXT_WRAP_TRUNCATE TextWrapping = 1 // Truncate with ellipsis
	TextWrapping_TEXT_WRAP_WORD     TextWrapping = 2 // Wrap at word boundaries
)

// Enum value maps for TextWrapping.
var (
	TextWrapping_name = map[int32]string{
		0: "TEXT_WRAP_OFF",
		1: "TEXT_WRAP_TRUNCATE",
		2: "TEXT_WRAP_WORD",
	}
	TextWrapping_value = map[string]int32{
		"TEXT_WRAP_OFF":      0,
		"TEXT_WRAP_TRUNCATE": 1,
		"TEXT_WRAP_WORD":     2,
	}
)

func (x TextWrapping) Enum() *TextWrapping {
	p := new(TextWrapping)
	*p = x
	return p
}

func (x TextWrapping) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextWrapping) Descriptor() protoreflect.EnumDescriptor {
	return file_bridge_proto_enumTypes[1].Descriptor()
}

func (TextWrapping) Type() protoreflect.EnumType {
	return &file_bridge_proto_enumTypes[1]
}

func (x TextWrapping) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TextWrapping.Descriptor instead.
func (TextWrapping) EnumDescriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{1}
}

// Common response message
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Result        map[string]string      `protobuf:"bytes,3,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Response) GetResult() map[string]string {
	if x != nil {
		return x.Result
	}
	return nil
}

// Window operations
type CreateWindowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowId      string                 `protobuf:"bytes,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	FixedSize     bool                   `protobuf:"varint,5,opt,name=fixed_size,json=fixedSize,proto3" json:"fixed_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWindowRequest) Reset() {
	*x = CreateWindowRequest{}
	mi := &file_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWindowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWindowRequest) ProtoMessage() {}

func (x *CreateWindowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWindowRequest.ProtoReflect.Descriptor instead.
func (*CreateWindowRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWindowRequest) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

func (x *CreateWindowRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateWindowRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CreateWindowRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CreateWindowRequest) GetFixedSize() bool {
	if x != nil {
		return x.FixedSize
	}
	return false
}

type ShowWindowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowId      string                 `protobuf:"bytes,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowWindowRequest) Reset() {
	*x = ShowWindowRequest{}
	mi := &file_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowWindowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowWindowRequest) ProtoMessage() {}

func (x *ShowWindowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowWindowRequest.ProtoReflect.Descriptor instead.
func (*ShowWindowRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *ShowWindowRequest) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

type SetContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowId      string                 `protobuf:"bytes,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	WidgetId      string                 `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetContentRequest) Reset() {
	*x = SetContentRequest{}
	mi := &file_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetContentRequest) ProtoMessage() {}

func (x *SetContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetContentRequest.ProtoReflect.Descriptor instead.
func (*SetContentRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *SetContentRequest) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

func (x *SetContentRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

type ResizeWindowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowId      string                 `protobuf:"bytes,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeWindowRequest) Reset() {
	*x = ResizeWindowRequest{}
	mi := &file_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeWindowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeWindowRequest) ProtoMessage() {}

func (x *ResizeWindowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeWindowRequest.ProtoReflect.Descriptor instead.
func (*ResizeWindowRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *ResizeWindowRequest) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

func (x *ResizeWindowRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ResizeWindowRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type SetWindowTitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowId      string                 `protobuf:"bytes,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWindowTitleRequest) Reset() {
	*x = SetWindowTitleRequest{}
	mi := &file_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWindowTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWindowTitleRequest) ProtoMessage() {}

func (x *SetWindowTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWindowTitleRequest.ProtoReflect.Descriptor instead.
func (*SetWindowTitleRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *SetWindowTitleRequest) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

func (x *SetWindowTitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CenterWindowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowId      string                 `protobuf:"bytes,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CenterWindowRequest) Reset() {
	*x = CenterWindowRequest{}
	mi := &file_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CenterWindowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CenterWindowRequest) ProtoMessage() {}

func (x *CenterWindowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CenterWindowRequest.ProtoReflect.Descriptor instead.
func (*CenterWindowRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *CenterWindowRequest) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

type SetWindowFullScreenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowId      string                 `protobuf:"bytes,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	Fullscreen    bool                   `protobuf:"varint,2,opt,name=fullscreen,proto3" json:"fullscreen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWindowFullScreenRequest) Reset() {
	*x = SetWindowFullScreenRequest{}
	mi := &file_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWindowFullScreenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWindowFullScreenRequest) ProtoMessage() {}

func (x *SetWindowFullScreenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWindowFullScreenRequest.ProtoReflect.Descriptor instead.
func (*SetWindowFullScreenRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{7}
}

func (x *SetWindowFullScreenRequest) GetWindowId() string {
	if x != nil {
		return x.WindowId
	}
	return ""
}

func (x *SetWindowFullScreenRequest) GetFullscreen() bool {
	if x != nil {
		return x.Fullscreen
	}
	return false
}

// Widget creation messages
type CreateImageRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WidgetId string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*CreateImageRequest_InlineData
	//	*CreateImageRequest_ResourceName
	Source              isCreateImageRequest_Source `protobuf_oneof:"source"`
	Width               int32                       `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height              int32                       `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	CallbackId          string                      `protobuf:"bytes,6,opt,name=callback_id,json=callbackId,proto3" json:"callback_id,omitempty"`                                // Click callback
	DragCallbackId      string                      `protobuf:"bytes,7,opt,name=drag_callback_id,json=dragCallbackId,proto3" json:"drag_callback_id,omitempty"`                  // Drag callback
	DoubleTapCallbackId string                      `protobuf:"bytes,8,opt,name=double_tap_callback_id,json=doubleTapCallbackId,proto3" json:"double_tap_callback_id,omitempty"` // Double tap callback
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateImageRequest) Reset() {
	*x = CreateImageRequest{}
	mi := &file_bridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateImageRequest) ProtoMessage() {}

func (x *CreateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateImageRequest.ProtoReflect.Descriptor instead.
func (*CreateImageRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{8}
}

func (x *CreateImageRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

func (x *CreateImageRequest) GetSource() isCreateImageRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *CreateImageRequest) GetInlineData() []byte {
	if x != nil {
		if x, ok := x.Source.(*CreateImageRequest_InlineData); ok {
			return x.InlineData
		}
	}
	return nil
}

func (x *CreateImageRequest) GetResourceName() string {
	if x != nil {
		if x, ok := x.Source.(*CreateImageRequest_ResourceName); ok {
			return x.ResourceName
		}
	}
	return ""
}

func (x *CreateImageRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CreateImageRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CreateImageRequest) GetCallbackId() string {
	if x != nil {
		return x.CallbackId
	}
	return ""
}

func (x *CreateImageRequest) GetDragCallbackId() string {
	if x != nil {
		return x.DragCallbackId
	}
	return ""
}

func (x *CreateImageRequest) GetDoubleTapCallbackId() string {
	if x != nil {
		return x.DoubleTapCallbackId
	}
	return ""
}

type isCreateImageRequest_Source interface {
	isCreateImageRequest_Source()
}

type CreateImageRequest_InlineData struct {
	InlineData []byte `protobuf:"bytes,2,opt,name=inline_data,json=inlineData,proto3,oneof"` // Raw PNG/JPEG bytes
}

type CreateImageRequest_ResourceName struct {
	ResourceName string `protobuf:"bytes,3,opt,name=resource_name,json=resourceName,proto3,oneof"` // Reference to registered resource
}

func (*CreateImageRequest_InlineData) isCreateImageRequest_Source() {}

func (*CreateImageRequest_ResourceName) isCreateImageRequest_Source() {}

type CreateLabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Bold          bool                   `protobuf:"varint,3,opt,name=bold,proto3" json:"bold,omitempty"`
	Alignment     TextAlignment          `protobuf:"varint,4,opt,name=alignment,proto3,enum=bridge.TextAlignment" json:"alignment,omitempty"`
	Italic        bool                   `protobuf:"varint,5,opt,name=italic,proto3" json:"italic,omitempty"`
	Monospace     bool                   `protobuf:"varint,6,opt,name=monospace,proto3" json:"monospace,omitempty"`
	Wrapping      TextWrapping           `protobuf:"varint,7,opt,name=wrapping,proto3,enum=bridge.TextWrapping" json:"wrapping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLabelRequest) Reset() {
	*x = CreateLabelRequest{}
	mi := &file_bridge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLabelRequest) ProtoMessage() {}

func (x *CreateLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLabelRequest.ProtoReflect.Descriptor instead.
func (*CreateLabelRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{9}
}

func (x *CreateLabelRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

func (x *CreateLabelRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreateLabelRequest) GetBold() bool {
	if x != nil {
		return x.Bold
	}
	return false
}

func (x *CreateLabelRequest) GetAlignment() TextAlignment {
	if x != nil {
		return x.Alignment
	}
	return TextAlignment_TEXT_ALIGN_LEADING
}

func (x *CreateLabelRequest) GetItalic() bool {
	if x != nil {
		return x.Italic
	}
	return false
}

func (x *CreateLabelRequest) GetMonospace() bool {
	if x != nil {
		return x.Monospace
	}
	return false
}

func (x *CreateLabelRequest) GetWrapping() TextWrapping {
	if x != nil {
		return x.Wrapping
	}
	return TextWrapping_TEXT_WRAP_OFF
}

type CreateButtonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	CallbackId    string                 `protobuf:"bytes,3,opt,name=callback_id,json=callbackId,proto3" json:"callback_id,omitempty"`
	Important     bool                   `protobuf:"varint,4,opt,name=important,proto3" json:"important,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateButtonRequest) Reset() {
	*x = CreateButtonRequest{}
	mi := &file_bridge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateButtonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateButtonRequest) ProtoMessage() {}

func (x *CreateButtonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateButtonRequest.ProtoReflect.Descriptor instead.
func (*CreateButtonRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{10}
}

func (x *CreateButtonRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

func (x *CreateButtonRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreateButtonRequest) GetCallbackId() string {
	if x != nil {
		return x.CallbackId
	}
	return ""
}

func (x *CreateButtonRequest) GetImportant() bool {
	if x != nil {
		return x.Important
	}
	return false
}

type CreateEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Placeholder   string                 `protobuf:"bytes,2,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	CallbackId    string                 `protobuf:"bytes,3,opt,name=callback_id,json=callbackId,proto3" json:"callback_id,omitempty"` // Submit callback
	Width         int32                  `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Multiline     bool                   `protobuf:"varint,5,opt,name=multiline,proto3" json:"multiline,omitempty"`
	Password      bool                   `protobuf:"varint,6,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEntryRequest) Reset() {
	*x = CreateEntryRequest{}
	mi := &file_bridge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntryRequest) ProtoMessage() {}

func (x *CreateEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntryRequest.ProtoReflect.Descriptor instead.
func (*CreateEntryRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{11}
}

func (x *CreateEntryRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

func (x *CreateEntryRequest) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *CreateEntryRequest) GetCallbackId() string {
	if x != nil {
		return x.CallbackId
	}
	return ""
}

func (x *CreateEntryRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CreateEntryRequest) GetMultiline() bool {
	if x != nil {
		return x.Multiline
	}
	return false
}

func (x *CreateEntryRequest) GetPassword() bool {
	if x != nil {
		return x.Password
	}
	return false
}

type CreateVBoxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVBoxRequest) Reset() {
	*x = CreateVBoxRequest{}
	mi := &file_bridge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVBoxRequest) ProtoMessage() {}

func (x *CreateVBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVBoxRequest.ProtoReflect.Descriptor instead.
func (*CreateVBoxRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{12}
}

func (x *CreateVBoxRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

type CreateHBoxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHBoxRequest) Reset() {
	*x = CreateHBoxRequest{}
	mi := &file_bridge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHBoxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHBoxRequest) ProtoMessage() {}

func (x *CreateHBoxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHBoxRequest.ProtoReflect.Descriptor instead.
func (*CreateHBoxRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{13}
}

func (x *CreateHBoxRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

type CreateCheckboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Checked       bool                   `protobuf:"varint,3,opt,name=checked,proto3" json:"checked,omitempty"`
	CallbackId    string                 `protobuf:"bytes,4,opt,name=callback_id,json=callbackId,proto3" json:"callback_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCheckboxRequest) Reset() {
	*x = CreateCheckboxRequest{}
	mi := &file_bridge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckboxRequest) ProtoMessage() {}

func (x *CreateCheckboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckboxRequest.ProtoReflect.Descriptor instead.
func (*CreateCheckboxRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{14}
}

func (x *CreateCheckboxRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

func (x *CreateCheckboxRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreateCheckboxRequest) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

func (x *CreateCheckboxRequest) GetCallbackId() string {
	if x != nil {
		return x.CallbackId
	}
	return ""
}

type CreateSelectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Options       []string               `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	Selected      int32                  `protobuf:"varint,3,opt,name=selected,proto3" json:"selected,omitempty"`
	CallbackId    string                 `protobuf:"bytes,4,opt,name=callback_id,json=callbackId,proto3" json:"callback_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSelectRequest) Reset() {
	*x = CreateSelectRequest{}
	mi := &file_bridge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSelectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSelectRequest) ProtoMessage() {}

func (x *CreateSelectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSelectRequest.ProtoReflect.Descriptor instead.
func (*CreateSelectRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{15}
}

func (x *CreateSelectRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

func (x *CreateSelectRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CreateSelectRequest) GetSelected() int32 {
	if x != nil {
		return x.Selected
	}
	return 0
}

func (x *CreateSelectRequest) GetCallbackId() string {
	if x != nil {
		return x.CallbackId
	}
	return ""
}

// Resource messages
type RegisterResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // Raw image bytes (not base64!)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResourceRequest) Reset() {
	*x = RegisterResourceRequest{}
	mi := &file_bridge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResourceRequest) ProtoMessage() {}

func (x *RegisterResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResourceRequest.ProtoReflect.Descriptor instead.
func (*RegisterResourceRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterResourceRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UnregisterResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResourceRequest) Reset() {
	*x = UnregisterResourceRequest{}
	mi := &file_bridge_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResourceRequest) ProtoMessage() {}

func (x *UnregisterResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResourceRequest.ProtoReflect.Descriptor instead.
func (*UnregisterResourceRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{17}
}

func (x *UnregisterResourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Widget update messages
type UpdateImageRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WidgetId string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*UpdateImageRequest_InlineData
	//	*UpdateImageRequest_ResourceName
	Source        isUpdateImageRequest_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateImageRequest) Reset() {
	*x = UpdateImageRequest{}
	mi := &file_bridge_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateImageRequest) ProtoMessage() {}

func (x *UpdateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateImageRequest.ProtoReflect.Descriptor instead.
func (*UpdateImageRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateImageRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

func (x *UpdateImageRequest) GetSource() isUpdateImageRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *UpdateImageRequest) GetInlineData() []byte {
	if x != nil {
		if x, ok := x.Source.(*UpdateImageRequest_InlineData); ok {
			return x.InlineData
		}
	}
	return nil
}

func (x *UpdateImageRequest) GetResourceName() string {
	if x != nil {
		if x, ok := x.Source.(*UpdateImageRequest_ResourceName); ok {
			return x.ResourceName
		}
	}
	return ""
}

type isUpdateImageRequest_Source interface {
	isUpdateImageRequest_Source()
}

type UpdateImageRequest_InlineData struct {
	InlineData []byte `protobuf:"bytes,2,opt,name=inline_data,json=inlineData,proto3,oneof"`
}

type UpdateImageRequest_ResourceName struct {
	ResourceName string `protobuf:"bytes,3,opt,name=resource_name,json=resourceName,proto3,oneof"`
}

func (*UpdateImageRequest_InlineData) isUpdateImageRequest_Source() {}

func (*UpdateImageRequest_ResourceName) isUpdateImageRequest_Source() {}

type SetTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTextRequest) Reset() {
	*x = SetTextRequest{}
	mi := &file_bridge_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTextRequest) ProtoMessage() {}

func (x *SetTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTextRequest.ProtoReflect.Descriptor instead.
func (*SetTextRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{19}
}

func (x *SetTextRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

func (x *SetTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GetTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTextRequest) Reset() {
	*x = GetTextRequest{}
	mi := &file_bridge_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTextRequest) ProtoMessage() {}

func (x *GetTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTextRequest.ProtoReflect.Descriptor instead.
func (*GetTextRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{20}
}

func (x *GetTextRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

type GetTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTextResponse) Reset() {
	*x = GetTextResponse{}
	mi := &file_bridge_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTextResponse) ProtoMessage() {}

func (x *GetTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTextResponse.ProtoReflect.Descriptor instead.
func (*GetTextResponse) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{21}
}

func (x *GetTextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTextResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetTextResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SetProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProgressRequest) Reset() {
	*x = SetProgressRequest{}
	mi := &file_bridge_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProgressRequest) ProtoMessage() {}

func (x *SetProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProgressRequest.ProtoReflect.Descriptor instead.
func (*SetProgressRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{22}
}

func (x *SetProgressRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

func (x *SetProgressRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressRequest) Reset() {
	*x = GetProgressRequest{}
	mi := &file_bridge_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressRequest) ProtoMessage() {}

func (x *GetProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressRequest.ProtoReflect.Descriptor instead.
func (*GetProgressRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{23}
}

func (x *GetProgressRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

type GetProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressResponse) Reset() {
	*x = GetProgressResponse{}
	mi := &file_bridge_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressResponse) ProtoMessage() {}

func (x *GetProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressResponse.ProtoReflect.Descriptor instead.
func (*GetProgressResponse) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{24}
}

func (x *GetProgressResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetProgressResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetProgressResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SetCheckedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Checked       bool                   `protobuf:"varint,2,opt,name=checked,proto3" json:"checked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCheckedRequest) Reset() {
	*x = SetCheckedRequest{}
	mi := &file_bridge_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCheckedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCheckedRequest) ProtoMessage() {}

func (x *SetCheckedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCheckedRequest.ProtoReflect.Descriptor instead.
func (*SetCheckedRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{25}
}

func (x *SetCheckedRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

func (x *SetCheckedRequest) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

type GetCheckedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckedRequest) Reset() {
	*x = GetCheckedRequest{}
	mi := &file_bridge_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckedRequest) ProtoMessage() {}

func (x *GetCheckedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckedRequest.ProtoReflect.Descriptor instead.
func (*GetCheckedRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{26}
}

func (x *GetCheckedRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

type GetCheckedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Checked       bool                   `protobuf:"varint,3,opt,name=checked,proto3" json:"checked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckedResponse) Reset() {
	*x = GetCheckedResponse{}
	mi := &file_bridge_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckedResponse) ProtoMessage() {}

func (x *GetCheckedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckedResponse.ProtoReflect.Descriptor instead.
func (*GetCheckedResponse) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{27}
}

func (x *GetCheckedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetCheckedResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetCheckedResponse) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

// Interaction messages
type ClickWidgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickWidgetRequest) Reset() {
	*x = ClickWidgetRequest{}
	mi := &file_bridge_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickWidgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickWidgetRequest) ProtoMessage() {}

func (x *ClickWidgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickWidgetRequest.ProtoReflect.Descriptor instead.
func (*ClickWidgetRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{28}
}

func (x *ClickWidgetRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

type TypeTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeTextRequest) Reset() {
	*x = TypeTextRequest{}
	mi := &file_bridge_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeTextRequest) ProtoMessage() {}

func (x *TypeTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeTextRequest.ProtoReflect.Descriptor instead.
func (*TypeTextRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{29}
}

func (x *TypeTextRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

func (x *TypeTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type DoubleTapWidgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoubleTapWidgetRequest) Reset() {
	*x = DoubleTapWidgetRequest{}
	mi := &file_bridge_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoubleTapWidgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleTapWidgetRequest) ProtoMessage() {}

func (x *DoubleTapWidgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleTapWidgetRequest.ProtoReflect.Descriptor instead.
func (*DoubleTapWidgetRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{30}
}

func (x *DoubleTapWidgetRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

type RightClickWidgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RightClickWidgetRequest) Reset() {
	*x = RightClickWidgetRequest{}
	mi := &file_bridge_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RightClickWidgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RightClickWidgetRequest) ProtoMessage() {}

func (x *RightClickWidgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RightClickWidgetRequest.ProtoReflect.Descriptor instead.
func (*RightClickWidgetRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{31}
}

func (x *RightClickWidgetRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

type DragWidgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	DeltaX        int32                  `protobuf:"varint,2,opt,name=delta_x,json=deltaX,proto3" json:"delta_x,omitempty"`
	DeltaY        int32                  `protobuf:"varint,3,opt,name=delta_y,json=deltaY,proto3" json:"delta_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DragWidgetRequest) Reset() {
	*x = DragWidgetRequest{}
	mi := &file_bridge_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DragWidgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragWidgetRequest) ProtoMessage() {}

func (x *DragWidgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragWidgetRequest.ProtoReflect.Descriptor instead.
func (*DragWidgetRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{32}
}

func (x *DragWidgetRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

func (x *DragWidgetRequest) GetDeltaX() int32 {
	if x != nil {
		return x.DeltaX
	}
	return 0
}

func (x *DragWidgetRequest) GetDeltaY() int32 {
	if x != nil {
		return x.DeltaY
	}
	return 0
}

// Custom ID messages
type RegisterCustomIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomId      string                 `protobuf:"bytes,1,opt,name=custom_id,json=customId,proto3" json:"custom_id,omitempty"`
	WidgetId      string                 `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCustomIdRequest) Reset() {
	*x = RegisterCustomIdRequest{}
	mi := &file_bridge_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCustomIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCustomIdRequest) ProtoMessage() {}

func (x *RegisterCustomIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCustomIdRequest.ProtoReflect.Descriptor instead.
func (*RegisterCustomIdRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{33}
}

func (x *RegisterCustomIdRequest) GetCustomId() string {
	if x != nil {
		return x.CustomId
	}
	return ""
}

func (x *RegisterCustomIdRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

// Query messages
type FindWidgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      string                 `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "text", "id", "type", "exactText"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindWidgetRequest) Reset() {
	*x = FindWidgetRequest{}
	mi := &file_bridge_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindWidgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindWidgetRequest) ProtoMessage() {}

func (x *FindWidgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindWidgetRequest.ProtoReflect.Descriptor instead.
func (*FindWidgetRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{34}
}

func (x *FindWidgetRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *FindWidgetRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type FindWidgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	WidgetIds     []string               `protobuf:"bytes,3,rep,name=widget_ids,json=widgetIds,proto3" json:"widget_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindWidgetResponse) Reset() {
	*x = FindWidgetResponse{}
	mi := &file_bridge_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindWidgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindWidgetResponse) ProtoMessage() {}

func (x *FindWidgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindWidgetResponse.ProtoReflect.Descriptor instead.
func (*FindWidgetResponse) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{35}
}

func (x *FindWidgetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FindWidgetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FindWidgetResponse) GetWidgetIds() []string {
	if x != nil {
		return x.WidgetIds
	}
	return nil
}

type GetWidgetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWidgetInfoRequest) Reset() {
	*x = GetWidgetInfoRequest{}
	mi := &file_bridge_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWidgetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWidgetInfoRequest) ProtoMessage() {}

func (x *GetWidgetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWidgetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetWidgetInfoRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{36}
}

func (x *GetWidgetInfoRequest) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

type WidgetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	X             float32                `protobuf:"fixed32,6,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,7,opt,name=y,proto3" json:"y,omitempty"`
	Width         float32                `protobuf:"fixed32,8,opt,name=width,proto3" json:"width,omitempty"`
	Height        float32                `protobuf:"fixed32,9,opt,name=height,proto3" json:"height,omitempty"`
	Visible       bool                   `protobuf:"varint,10,opt,name=visible,proto3" json:"visible,omitempty"`
	Enabled       bool                   `protobuf:"varint,11,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetInfoResponse) Reset() {
	*x = WidgetInfoResponse{}
	mi := &file_bridge_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetInfoResponse) ProtoMessage() {}

func (x *WidgetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetInfoResponse.ProtoReflect.Descriptor instead.
func (*WidgetInfoResponse) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{37}
}

func (x *WidgetInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WidgetInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WidgetInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WidgetInfoResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WidgetInfoResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *WidgetInfoResponse) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *WidgetInfoResponse) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *WidgetInfoResponse) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *WidgetInfoResponse) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *WidgetInfoResponse) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *WidgetInfoResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type GetAllWidgetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllWidgetsRequest) Reset() {
	*x = GetAllWidgetsRequest{}
	mi := &file_bridge_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllWidgetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllWidgetsRequest) ProtoMessage() {}

func (x *GetAllWidgetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllWidgetsRequest.ProtoReflect.Descriptor instead.
func (*GetAllWidgetsRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{38}
}

type GetAllWidgetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Widgets       []*WidgetInfo          `protobuf:"bytes,3,rep,name=widgets,proto3" json:"widgets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllWidgetsResponse) Reset() {
	*x = GetAllWidgetsResponse{}
	mi := &file_bridge_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllWidgetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllWidgetsResponse) ProtoMessage() {}

func (x *GetAllWidgetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllWidgetsResponse.ProtoReflect.Descriptor instead.
func (*GetAllWidgetsResponse) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{39}
}

func (x *GetAllWidgetsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAllWidgetsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetAllWidgetsResponse) GetWidgets() []*WidgetInfo {
	if x != nil {
		return x.Widgets
	}
	return nil
}

type WidgetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetInfo) Reset() {
	*x = WidgetInfo{}
	mi := &file_bridge_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetInfo) ProtoMessage() {}

func (x *WidgetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetInfo.ProtoReflect.Descriptor instead.
func (*WidgetInfo) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{40}
}

func (x *WidgetInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WidgetInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WidgetInfo) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Event streaming
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "callback", "windowClosed", etc.
	WidgetId      string                 `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Data          map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_bridge_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{41}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

func (x *Event) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type EventSubscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTypes    []string               `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"` // Which events to subscribe to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventSubscription) Reset() {
	*x = EventSubscription{}
	mi := &file_bridge_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSubscription) ProtoMessage() {}

func (x *EventSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSubscription.ProtoReflect.Descriptor instead.
func (*EventSubscription) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{42}
}

func (x *EventSubscription) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

// Lifecycle
type QuitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuitRequest) Reset() {
	*x = QuitRequest{}
	mi := &file_bridge_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitRequest) ProtoMessage() {}

func (x *QuitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bridge_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitRequest.ProtoReflect.Descriptor instead.
func (*QuitRequest) Descriptor() ([]byte, []int) {
	return file_bridge_proto_rawDescGZIP(), []int{43}
}

var File_bridge_proto protoreflect.FileDescriptor

const file_bridge_proto_rawDesc = "" +
	"\n" +
	"\fbridge.proto\x12\x06bridge\"\xab\x01\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x124\n" +
	"\x06result\x18\x03 \x03(\v2\x1c.bridge.Response.ResultEntryR\x06result\x1a9\n" +
	"\vResultEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x95\x01\n" +
	"\x13CreateWindowRequest\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\tR\bwindowId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x1d\n" +
	"\n" +
	"fixed_size\x18\x05 \x01(\bR\tfixedSize\"0\n" +
	"\x11ShowWindowRequest\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\tR\bwindowId\"M\n" +
	"\x11SetContentRequest\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\tR\bwindowId\x12\x1b\n" +
	"\twidget_id\x18\x02 \x01(\tR\bwidgetId\"`\n" +
	"\x13ResizeWindowRequest\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\tR\bwindowId\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\"J\n" +
	"\x15SetWindowTitleRequest\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\tR\bwindowId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"2\n" +
	"\x13CenterWindowRequest\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\tR\bwindowId\"Y\n" +
	"\x1aSetWindowFullScreenRequest\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\tR\bwindowId\x12\x1e\n" +
	"\n" +
	"fullscreen\x18\x02 \x01(\bR\n" +
	"fullscreen\"\xb3\x02\n" +
	"\x12CreateImageRequest\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\x12!\n" +
	"\vinline_data\x18\x02 \x01(\fH\x00R\n" +
	"inlineData\x12%\n" +
	"\rresource_name\x18\x03 \x01(\tH\x00R\fresourceName\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height\x12\x1f\n" +
	"\vcallback_id\x18\x06 \x01(\tR\n" +
	"callbackId\x12(\n" +
	"\x10drag_callback_id\x18\a \x01(\tR\x0edragCallbackId\x123\n" +
	"\x16double_tap_callback_id\x18\b \x01(\tR\x13doubleTapCallbackIdB\b\n" +
	"\x06source\"\xf6\x01\n" +
	"\x12CreateLabelRequest\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04bold\x18\x03 \x01(\bR\x04bold\x123\n" +
	"\talignment\x18\x04 \x01(\x0e2\x15.bridge.TextAlignmentR\talignment\x12\x16\n" +
	"\x06italic\x18\x05 \x01(\bR\x06italic\x12\x1c\n" +
	"\tmonospace\x18\x06 \x01(\bR\tmonospace\x120\n" +
	"\bwrapping\x18\a \x01(\x0e2\x14.bridge.TextWrappingR\bwrapping\"\x85\x01\n" +
	"\x13CreateButtonRequest\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1f\n" +
	"\vcallback_id\x18\x03 \x01(\tR\n" +
	"callbackId\x12\x1c\n" +
	"\timportant\x18\x04 \x01(\bR\timportant\"\xc4\x01\n" +
	"\x12CreateEntryRequest\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\x12 \n" +
	"\vplaceholder\x18\x02 \x01(\tR\vplaceholder\x12\x1f\n" +
	"\vcallback_id\x18\x03 \x01(\tR\n" +
	"callbackId\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x1c\n" +
	"\tmultiline\x18\x05 \x01(\bR\tmultiline\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\bR\bpassword\"0\n" +
	"\x11CreateVBoxRequest\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\"0\n" +
	"\x11CreateHBoxRequest\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\"\x83\x01\n" +
	"\x15CreateCheckboxRequest\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x18\n" +
	"\achecked\x18\x03 \x01(\bR\achecked\x12\x1f\n" +
	"\vcallback_id\x18\x04 \x01(\tR\n" +
	"callbackId\"\x89\x01\n" +
	"\x13CreateSelectRequest\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\x12\x18\n" +
	"\aoptions\x18\x02 \x03(\tR\aoptions\x12\x1a\n" +
	"\bselected\x18\x03 \x01(\x05R\bselected\x12\x1f\n" +
	"\vcallback_id\x18\x04 \x01(\tR\n" +
	"callbackId\"A\n" +
	"\x17RegisterResourceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"/\n" +
	"\x19UnregisterResourceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x85\x01\n" +
	"\x12UpdateImageRequest\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\x12!\n" +
	"\vinline_data\x18\x02 \x01(\fH\x00R\n" +
	"inlineData\x12%\n" +
	"\rresource_name\x18\x03 \x01(\tH\x00R\fresourceNameB\b\n" +
	"\x06source\"A\n" +
	"\x0eSetTextRequest\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"-\n" +
	"\x0eGetTextRequest\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\"U\n" +
	"\x0fGetTextResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"G\n" +
	"\x12SetProgressRequest\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"1\n" +
	"\x12GetProgressRequest\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\"[\n" +
	"\x13GetProgressResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\"J\n" +
	"\x11SetCheckedRequest\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\x12\x18\n" +
	"\achecked\x18\x02 \x01(\bR\achecked\"0\n" +
	"\x11GetCheckedRequest\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\"^\n" +
	"\x12GetCheckedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\achecked\x18\x03 \x01(\bR\achecked\"1\n" +
	"\x12ClickWidgetRequest\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\"B\n" +
	"\x0fTypeTextRequest\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"5\n" +
	"\x16DoubleTapWidgetRequest\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\"6\n" +
	"\x17RightClickWidgetRequest\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\"b\n" +
	"\x11DragWidgetRequest\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\x12\x17\n" +
	"\adelta_x\x18\x02 \x01(\x05R\x06deltaX\x12\x17\n" +
	"\adelta_y\x18\x03 \x01(\x05R\x06deltaY\"S\n" +
	"\x17RegisterCustomIdRequest\x12\x1b\n" +
	"\tcustom_id\x18\x01 \x01(\tR\bcustomId\x12\x1b\n" +
	"\twidget_id\x18\x02 \x01(\tR\bwidgetId\"C\n" +
	"\x11FindWidgetRequest\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"c\n" +
	"\x12FindWidgetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"widget_ids\x18\x03 \x03(\tR\twidgetIds\"3\n" +
	"\x14GetWidgetInfoRequest\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\"\xfa\x01\n" +
	"\x12WidgetInfoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\f\n" +
	"\x01x\x18\x06 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\a \x01(\x02R\x01y\x12\x14\n" +
	"\x05width\x18\b \x01(\x02R\x05width\x12\x16\n" +
	"\x06height\x18\t \x01(\x02R\x06height\x12\x18\n" +
	"\avisible\x18\n" +
	" \x01(\bR\avisible\x12\x18\n" +
	"\aenabled\x18\v \x01(\bR\aenabled\"\x16\n" +
	"\x14GetAllWidgetsRequest\"u\n" +
	"\x15GetAllWidgetsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12,\n" +
	"\awidgets\x18\x03 \x03(\v2\x12.bridge.WidgetInfoR\awidgets\"D\n" +
	"\n" +
	"WidgetInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\x9e\x01\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\twidget_id\x18\x02 \x01(\tR\bwidgetId\x12+\n" +
	"\x04data\x18\x03 \x03(\v2\x17.bridge.Event.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x11EventSubscription\x12\x1f\n" +
	"\vevent_types\x18\x01 \x03(\tR\n" +
	"eventTypes\"\r\n" +
	"\vQuitRequest*W\n" +
	"\rTextAlignment\x12\x16\n" +
	"\x12TEXT_ALIGN_LEADING\x10\x00\x12\x15\n" +
	"\x11TEXT_ALIGN_CENTER\x10\x01\x12\x17\n" +
	"\x13TEXT_ALIGN_TRAILING\x10\x02*M\n" +
	"\fTextWrapping\x12\x11\n" +
	"\rTEXT_WRAP_OFF\x10\x00\x12\x16\n" +
	"\x12TEXT_WRAP_TRUNCATE\x10\x01\x12\x12\n" +
	"\x0eTEXT_WRAP_WORD\x10\x022\xd3\x11\n" +
	"\rBridgeService\x12=\n" +
	"\fCreateWindow\x12\x1b.bridge.CreateWindowRequest\x1a\x10.bridge.Response\x129\n" +
	"\n" +
	"ShowWindow\x12\x19.bridge.ShowWindowRequest\x1a\x10.bridge.Response\x129\n" +
	"\n" +
	"SetContent\x12\x19.bridge.SetContentRequest\x1a\x10.bridge.Response\x12=\n" +
	"\fResizeWindow\x12\x1b.bridge.ResizeWindowRequest\x1a\x10.bridge.Response\x12A\n" +
	"\x0eSetWindowTitle\x12\x1d.bridge.SetWindowTitleRequest\x1a\x10.bridge.Response\x12=\n" +
	"\fCenterWindow\x12\x1b.bridge.CenterWindowRequest\x1a\x10.bridge.Response\x12K\n" +
	"\x13SetWindowFullScreen\x12\".bridge.SetWindowFullScreenRequest\x1a\x10.bridge.Response\x12;\n" +
	"\vCreateImage\x12\x1a.bridge.CreateImageRequest\x1a\x10.bridge.Response\x12;\n" +
	"\vCreateLabel\x12\x1a.bridge.CreateLabelRequest\x1a\x10.bridge.Response\x12=\n" +
	"\fCreateButton\x12\x1b.bridge.CreateButtonRequest\x1a\x10.bridge.Response\x12;\n" +
	"\vCreateEntry\x12\x1a.bridge.CreateEntryRequest\x1a\x10.bridge.Response\x129\n" +
	"\n" +
	"CreateVBox\x12\x19.bridge.CreateVBoxRequest\x1a\x10.bridge.Response\x129\n" +
	"\n" +
	"CreateHBox\x12\x19.bridge.CreateHBoxRequest\x1a\x10.bridge.Response\x12A\n" +
	"\x0eCreateCheckbox\x12\x1d.bridge.CreateCheckboxRequest\x1a\x10.bridge.Response\x12=\n" +
	"\fCreateSelect\x12\x1b.bridge.CreateSelectRequest\x1a\x10.bridge.Response\x12E\n" +
	"\x10RegisterResource\x12\x1f.bridge.RegisterResourceRequest\x1a\x10.bridge.Response\x12I\n" +
	"\x12UnregisterResource\x12!.bridge.UnregisterResourceRequest\x1a\x10.bridge.Response\x12;\n" +
	"\vUpdateImage\x12\x1a.bridge.UpdateImageRequest\x1a\x10.bridge.Response\x123\n" +
	"\aSetText\x12\x16.bridge.SetTextRequest\x1a\x10.bridge.Response\x12:\n" +
	"\aGetText\x12\x16.bridge.GetTextRequest\x1a\x17.bridge.GetTextResponse\x12;\n" +
	"\vSetProgress\x12\x1a.bridge.SetProgressRequest\x1a\x10.bridge.Response\x12F\n" +
	"\vGetProgress\x12\x1a.bridge.GetProgressRequest\x1a\x1b.bridge.GetProgressResponse\x129\n" +
	"\n" +
	"SetChecked\x12\x19.bridge.SetCheckedRequest\x1a\x10.bridge.Response\x12C\n" +
	"\n" +
	"GetChecked\x12\x19.bridge.GetCheckedRequest\x1a\x1a.bridge.GetCheckedResponse\x12;\n" +
	"\vClickWidget\x12\x1a.bridge.ClickWidgetRequest\x1a\x10.bridge.Response\x125\n" +
	"\bTypeText\x12\x17.bridge.TypeTextRequest\x1a\x10.bridge.Response\x12C\n" +
	"\x0fDoubleTapWidget\x12\x1e.bridge.DoubleTapWidgetRequest\x1a\x10.bridge.Response\x12E\n" +
	"\x10RightClickWidget\x12\x1f.bridge.RightClickWidgetRequest\x1a\x10.bridge.Response\x129\n" +
	"\n" +
	"DragWidget\x12\x19.bridge.DragWidgetRequest\x1a\x10.bridge.Response\x12E\n" +
	"\x10RegisterCustomId\x12\x1f.bridge.RegisterCustomIdRequest\x1a\x10.bridge.Response\x12C\n" +
	"\n" +
	"FindWidget\x12\x19.bridge.FindWidgetRequest\x1a\x1a.bridge.FindWidgetResponse\x12I\n" +
	"\rGetWidgetInfo\x12\x1c.bridge.GetWidgetInfoRequest\x1a\x1a.bridge.WidgetInfoResponse\x12L\n" +
	"\rGetAllWidgets\x12\x1c.bridge.GetAllWidgetsRequest\x1a\x1d.bridge.GetAllWidgetsResponse\x12=\n" +
	"\x0fSubscribeEvents\x12\x19.bridge.EventSubscription\x1a\r.bridge.Event0\x01\x12-\n" +
	"\x04Quit\x12\x13.bridge.QuitRequest\x1a\x10.bridge.ResponseB,Z*github.com/paul-hammant/tsyne/bridge/protob\x06proto3"

var (
	file_bridge_proto_rawDescOnce sync.Once
	file_bridge_proto_rawDescData []byte
)

func file_bridge_proto_rawDescGZIP() []byte {
	file_bridge_proto_rawDescOnce.Do(func() {
		file_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bridge_proto_rawDesc), len(file_bridge_proto_rawDesc)))
	})
	return file_bridge_proto_rawDescData
}

var file_bridge_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_bridge_proto_goTypes = []any{
	(TextAlignment)(0),                 // 0: bridge.TextAlignment
	(TextWrapping)(0),                  // 1: bridge.TextWrapping
	(*Response)(nil),                   // 2: bridge.Response
	(*CreateWindowRequest)(nil),        // 3: bridge.CreateWindowRequest
	(*ShowWindowRequest)(nil),          // 4: bridge.ShowWindowRequest
	(*SetContentRequest)(nil),          // 5: bridge.SetContentRequest
	(*ResizeWindowRequest)(nil),        // 6: bridge.ResizeWindowRequest
	(*SetWindowTitleRequest)(nil),      // 7: bridge.SetWindowTitleRequest
	(*CenterWindowRequest)(nil),        // 8: bridge.CenterWindowRequest
	(*SetWindowFullScreenRequest)(nil), // 9: bridge.SetWindowFullScreenRequest
	(*CreateImageRequest)(nil),         // 10: bridge.CreateImageRequest
	(*CreateLabelRequest)(nil),         // 11: bridge.CreateLabelRequest
	(*CreateButtonRequest)(nil),        // 12: bridge.CreateButtonRequest
	(*CreateEntryRequest)(nil),         // 13: bridge.CreateEntryRequest
	(*CreateVBoxRequest)(nil),          // 14: bridge.CreateVBoxRequest
	(*CreateHBoxRequest)(nil),          // 15: bridge.CreateHBoxRequest
	(*CreateCheckboxRequest)(nil),      // 16: bridge.CreateCheckboxRequest
	(*CreateSelectRequest)(nil),        // 17: bridge.CreateSelectRequest
	(*RegisterResourceRequest)(nil),    // 18: bridge.RegisterResourceRequest
	(*UnregisterResourceRequest)(nil),  // 19: bridge.UnregisterResourceRequest
	(*UpdateImageRequest)(nil),         // 20: bridge.UpdateImageRequest
	(*SetTextRequest)(nil),             // 21: bridge.SetTextRequest
	(*GetTextRequest)(nil),             // 22: bridge.GetTextRequest
	(*GetTextResponse)(nil),            // 23: bridge.GetTextResponse
	(*SetProgressRequest)(nil),         // 24: bridge.SetProgressRequest
	(*GetProgressRequest)(nil),         // 25: bridge.GetProgressRequest
	(*GetProgressResponse)(nil),        // 26: bridge.GetProgressResponse
	(*SetCheckedRequest)(nil),          // 27: bridge.SetCheckedRequest
	(*GetCheckedRequest)(nil),          // 28: bridge.GetCheckedRequest
	(*GetCheckedResponse)(nil),         // 29: bridge.GetCheckedResponse
	(*ClickWidgetRequest)(nil),         // 30: bridge.ClickWidgetRequest
	(*TypeTextRequest)(nil),            // 31: bridge.TypeTextRequest
	(*DoubleTapWidgetRequest)(nil),     // 32: bridge.DoubleTapWidgetRequest
	(*RightClickWidgetRequest)(nil),    // 33: bridge.RightClickWidgetRequest
	(*DragWidgetRequest)(nil),          // 34: bridge.DragWidgetRequest
	(*RegisterCustomIdRequest)(nil),    // 35: bridge.RegisterCustomIdRequest
	(*FindWidgetRequest)(nil),          // 36: bridge.FindWidgetRequest
	(*FindWidgetResponse)(nil),         // 37: bridge.FindWidgetResponse
	(*GetWidgetInfoRequest)(nil),       // 38: bridge.GetWidgetInfoRequest
	(*WidgetInfoResponse)(nil),         // 39: bridge.WidgetInfoResponse
	(*GetAllWidgetsRequest)(nil),       // 40: bridge.GetAllWidgetsRequest
	(*GetAllWidgetsResponse)(nil),      // 41: bridge.GetAllWidgetsResponse
	(*WidgetInfo)(nil),                 // 42: bridge.WidgetInfo
	(*Event)(nil),                      // 43: bridge.Event
	(*EventSubscription)(nil),          // 44: bridge.EventSubscription
	(*QuitRequest)(nil),                // 45: bridge.QuitRequest
	nil,                                // 46: bridge.Response.ResultEntry
	nil,                                // 47: bridge.Event.DataEntry
}
var file_bridge_proto_depIdxs = []int32{
	46, // 0: bridge.Response.result:type_name -> bridge.Response.ResultEntry
	0,  // 1: bridge.CreateLabelRequest.alignment:type_name -> bridge.TextAlignment
	1,  // 2: bridge.CreateLabelRequest.wrapping:type_name -> bridge.TextWrapping
	42, // 3: bridge.GetAllWidgetsResponse.widgets:type_name -> bridge.WidgetInfo
	47, // 4: bridge.Event.data:type_name -> bridge.Event.DataEntry
	3,  // 5: bridge.BridgeService.CreateWindow:input_type -> bridge.CreateWindowRequest
	4,  // 6: bridge.BridgeService.ShowWindow:input_type -> bridge.ShowWindowRequest
	5,  // 7: bridge.BridgeService.SetContent:input_type -> bridge.SetContentRequest
	6,  // 8: bridge.BridgeService.ResizeWindow:input_type -> bridge.ResizeWindowRequest
	7,  // 9: bridge.BridgeService.SetWindowTitle:input_type -> bridge.SetWindowTitleRequest
	8,  // 10: bridge.BridgeService.CenterWindow:input_type -> bridge.CenterWindowRequest
	9,  // 11: bridge.BridgeService.SetWindowFullScreen:input_type -> bridge.SetWindowFullScreenRequest
	10, // 12: bridge.BridgeService.CreateImage:input_type -> bridge.CreateImageRequest
	11, // 13: bridge.BridgeService.CreateLabel:input_type -> bridge.CreateLabelRequest
	12, // 14: bridge.BridgeService.CreateButton:input_type -> bridge.CreateButtonRequest
	13, // 15: bridge.BridgeService.CreateEntry:input_type -> bridge.CreateEntryRequest
	14, // 16: bridge.BridgeService.CreateVBox:input_type -> bridge.CreateVBoxRequest
	15, // 17: bridge.BridgeService.CreateHBox:input_type -> bridge.CreateHBoxRequest
	16, // 18: bridge.BridgeService.CreateCheckbox:input_type -> bridge.CreateCheckboxRequest
	17, // 19: bridge.BridgeService.CreateSelect:input_type -> bridge.CreateSelectRequest
	18, // 20: bridge.BridgeService.RegisterResource:input_type -> bridge.RegisterResourceRequest
	19, // 21: bridge.BridgeService.UnregisterResource:input_type -> bridge.UnregisterResourceRequest
	20, // 22: bridge.BridgeService.UpdateImage:input_type -> bridge.UpdateImageRequest
	21, // 23: bridge.BridgeService.SetText:input_type -> bridge.SetTextRequest
	22, // 24: bridge.BridgeService.GetText:input_type -> bridge.GetTextRequest
	24, // 25: bridge.BridgeService.SetProgress:input_type -> bridge.SetProgressRequest
	25, // 26: bridge.BridgeService.GetProgress:input_type -> bridge.GetProgressRequest
	27, // 27: bridge.BridgeService.SetChecked:input_type -> bridge.SetCheckedRequest
	28, // 28: bridge.BridgeService.GetChecked:input_type -> bridge.GetCheckedRequest
	30, // 29: bridge.BridgeService.ClickWidget:input_type -> bridge.ClickWidgetRequest
	31, // 30: bridge.BridgeService.TypeText:input_type -> bridge.TypeTextRequest
	32, // 31: bridge.BridgeService.DoubleTapWidget:input_type -> bridge.DoubleTapWidgetRequest
	33, // 32: bridge.BridgeService.RightClickWidget:input_type -> bridge.RightClickWidgetRequest
	34, // 33: bridge.BridgeService.DragWidget:input_type -> bridge.DragWidgetRequest
	35, // 34: bridge.BridgeService.RegisterCustomId:input_type -> bridge.RegisterCustomIdRequest
	36, // 35: bridge.BridgeService.FindWidget:input_type -> bridge.FindWidgetRequest
	38, // 36: bridge.BridgeService.GetWidgetInfo:input_type -> bridge.GetWidgetInfoRequest
	40, // 37: bridge.BridgeService.GetAllWidgets:input_type -> bridge.GetAllWidgetsRequest
	44, // 38: bridge.BridgeService.SubscribeEvents:input_type -> bridge.EventSubscription
	45, // 39: bridge.BridgeService.Quit:input_type -> bridge.QuitRequest
	2,  // 40: bridge.BridgeService.CreateWindow:output_type -> bridge.Response
	2,  // 41: bridge.BridgeService.ShowWindow:output_type -> bridge.Response
	2,  // 42: bridge.BridgeService.SetContent:output_type -> bridge.Response
	2,  // 43: bridge.BridgeService.ResizeWindow:output_type -> bridge.Response
	2,  // 44: bridge.BridgeService.SetWindowTitle:output_type -> bridge.Response
	2,  // 45: bridge.BridgeService.CenterWindow:output_type -> bridge.Response
	2,  // 46: bridge.BridgeService.SetWindowFullScreen:output_type -> bridge.Response
	2,  // 47: bridge.BridgeService.CreateImage:output_type -> bridge.Response
	2,  // 48: bridge.BridgeService.CreateLabel:output_type -> bridge.Response
	2,  // 49: bridge.BridgeService.CreateButton:output_type -> bridge.Response
	2,  // 50: bridge.BridgeService.CreateEntry:output_type -> bridge.Response
	2,  // 51: bridge.BridgeService.CreateVBox:output_type -> bridge.Response
	2,  // 52: bridge.BridgeService.CreateHBox:output_type -> bridge.Response
	2,  // 53: bridge.BridgeService.CreateCheckbox:output_type -> bridge.Response
	2,  // 54: bridge.BridgeService.CreateSelect:output_type -> bridge.Response
	2,  // 55: bridge.BridgeService.RegisterResource:output_type -> bridge.Response
	2,  // 56: bridge.BridgeService.UnregisterResource:output_type -> bridge.Response
	2,  // 57: bridge.BridgeService.UpdateImage:output_type -> bridge.Response
	2,  // 58: bridge.BridgeService.SetText:output_type -> bridge.Response
	23, // 59: bridge.BridgeService.GetText:output_type -> bridge.GetTextResponse
	2,  // 60: bridge.BridgeService.SetProgress:output_type -> bridge.Response
	26, // 61: bridge.BridgeService.GetProgress:output_type -> bridge.GetProgressResponse
	2,  // 62: bridge.BridgeService.SetChecked:output_type -> bridge.Response
	29, // 63: bridge.BridgeService.GetChecked:output_type -> bridge.GetCheckedResponse
	2,  // 64: bridge.BridgeService.ClickWidget:output_type -> bridge.Response
	2,  // 65: bridge.BridgeService.TypeText:output_type -> bridge.Response
	2,  // 66: bridge.BridgeService.DoubleTapWidget:output_type -> bridge.Response
	2,  // 67: bridge.BridgeService.RightClickWidget:output_type -> bridge.Response
	2,  // 68: bridge.BridgeService.DragWidget:output_type -> bridge.Response
	2,  // 69: bridge.BridgeService.RegisterCustomId:output_type -> bridge.Response
	37, // 70: bridge.BridgeService.FindWidget:output_type -> bridge.FindWidgetResponse
	39, // 71: bridge.BridgeService.GetWidgetInfo:output_type -> bridge.WidgetInfoResponse
	41, // 72: bridge.BridgeService.GetAllWidgets:output_type -> bridge.GetAllWidgetsResponse
	43, // 73: bridge.BridgeService.SubscribeEvents:output_type -> bridge.Event
	2,  // 74: bridge.BridgeService.Quit:output_type -> bridge.Response
	40, // [40:75] is the sub-list for method output_type
	5,  // [5:40] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_bridge_proto_init() }
func file_bridge_proto_init() {
	if File_bridge_proto != nil {
		return
	}
	file_bridge_proto_msgTypes[8].OneofWrappers = []any{
		(*CreateImageRequest_InlineData)(nil),
		(*CreateImageRequest_ResourceName)(nil),
	}
	file_bridge_proto_msgTypes[18].OneofWrappers = []any{
		(*UpdateImageRequest_InlineData)(nil),
		(*UpdateImageRequest_ResourceName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bridge_proto_rawDesc), len(file_bridge_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bridge_proto_goTypes,
		DependencyIndexes: file_bridge_proto_depIdxs,
		EnumInfos:         file_bridge_proto_enumTypes,
		MessageInfos:      file_bridge_proto_msgTypes,
	}.Build()
	File_bridge_proto = out.File
	file_bridge_proto_goTypes = nil
	file_bridge_proto_depIdxs = nil
}
