// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/bridge.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BridgeService_CreateWindow_FullMethodName          = "/bridge.BridgeService/CreateWindow"
	BridgeService_ShowWindow_FullMethodName            = "/bridge.BridgeService/ShowWindow"
	BridgeService_SetContent_FullMethodName            = "/bridge.BridgeService/SetContent"
	BridgeService_ResizeWindow_FullMethodName          = "/bridge.BridgeService/ResizeWindow"
	BridgeService_SetWindowTitle_FullMethodName        = "/bridge.BridgeService/SetWindowTitle"
	BridgeService_CenterWindow_FullMethodName          = "/bridge.BridgeService/CenterWindow"
	BridgeService_SetWindowFullScreen_FullMethodName   = "/bridge.BridgeService/SetWindowFullScreen"
	BridgeService_CreateImage_FullMethodName           = "/bridge.BridgeService/CreateImage"
	BridgeService_CreateLabel_FullMethodName           = "/bridge.BridgeService/CreateLabel"
	BridgeService_CreateButton_FullMethodName          = "/bridge.BridgeService/CreateButton"
	BridgeService_CreateEntry_FullMethodName           = "/bridge.BridgeService/CreateEntry"
	BridgeService_CreateVBox_FullMethodName            = "/bridge.BridgeService/CreateVBox"
	BridgeService_CreateHBox_FullMethodName            = "/bridge.BridgeService/CreateHBox"
	BridgeService_CreateCheckbox_FullMethodName        = "/bridge.BridgeService/CreateCheckbox"
	BridgeService_CreateSelect_FullMethodName          = "/bridge.BridgeService/CreateSelect"
	BridgeService_CreateScroll_FullMethodName          = "/bridge.BridgeService/CreateScroll"
	BridgeService_CreateGrid_FullMethodName            = "/bridge.BridgeService/CreateGrid"
	BridgeService_CreateCenter_FullMethodName          = "/bridge.BridgeService/CreateCenter"
	BridgeService_CreateClip_FullMethodName            = "/bridge.BridgeService/CreateClip"
	BridgeService_CreateMax_FullMethodName             = "/bridge.BridgeService/CreateMax"
	BridgeService_CreateStack_FullMethodName           = "/bridge.BridgeService/CreateStack"
	BridgeService_CreateCard_FullMethodName            = "/bridge.BridgeService/CreateCard"
	BridgeService_CreateAccordion_FullMethodName       = "/bridge.BridgeService/CreateAccordion"
	BridgeService_CreateForm_FullMethodName            = "/bridge.BridgeService/CreateForm"
	BridgeService_CreateBorder_FullMethodName          = "/bridge.BridgeService/CreateBorder"
	BridgeService_CreateGridWrap_FullMethodName        = "/bridge.BridgeService/CreateGridWrap"
	BridgeService_CreateAdaptiveGrid_FullMethodName    = "/bridge.BridgeService/CreateAdaptiveGrid"
	BridgeService_CreatePadded_FullMethodName          = "/bridge.BridgeService/CreatePadded"
	BridgeService_CreateSplit_FullMethodName           = "/bridge.BridgeService/CreateSplit"
	BridgeService_CreateTabs_FullMethodName            = "/bridge.BridgeService/CreateTabs"
	BridgeService_CreateDocTabs_FullMethodName         = "/bridge.BridgeService/CreateDocTabs"
	BridgeService_CreateThemeOverride_FullMethodName   = "/bridge.BridgeService/CreateThemeOverride"
	BridgeService_CreateInnerWindow_FullMethodName     = "/bridge.BridgeService/CreateInnerWindow"
	BridgeService_CreateNavigation_FullMethodName      = "/bridge.BridgeService/CreateNavigation"
	BridgeService_CreatePopup_FullMethodName           = "/bridge.BridgeService/CreatePopup"
	BridgeService_CreateMultipleWindows_FullMethodName = "/bridge.BridgeService/CreateMultipleWindows"
	BridgeService_RegisterResource_FullMethodName      = "/bridge.BridgeService/RegisterResource"
	BridgeService_UnregisterResource_FullMethodName    = "/bridge.BridgeService/UnregisterResource"
	BridgeService_UpdateImage_FullMethodName           = "/bridge.BridgeService/UpdateImage"
	BridgeService_SetText_FullMethodName               = "/bridge.BridgeService/SetText"
	BridgeService_GetText_FullMethodName               = "/bridge.BridgeService/GetText"
	BridgeService_SetProgress_FullMethodName           = "/bridge.BridgeService/SetProgress"
	BridgeService_GetProgress_FullMethodName           = "/bridge.BridgeService/GetProgress"
	BridgeService_SetChecked_FullMethodName            = "/bridge.BridgeService/SetChecked"
	BridgeService_GetChecked_FullMethodName            = "/bridge.BridgeService/GetChecked"
	BridgeService_ClickWidget_FullMethodName           = "/bridge.BridgeService/ClickWidget"
	BridgeService_TypeText_FullMethodName              = "/bridge.BridgeService/TypeText"
	BridgeService_DoubleTapWidget_FullMethodName       = "/bridge.BridgeService/DoubleTapWidget"
	BridgeService_RightClickWidget_FullMethodName      = "/bridge.BridgeService/RightClickWidget"
	BridgeService_DragWidget_FullMethodName            = "/bridge.BridgeService/DragWidget"
	BridgeService_RegisterCustomId_FullMethodName      = "/bridge.BridgeService/RegisterCustomId"
	BridgeService_FindWidget_FullMethodName            = "/bridge.BridgeService/FindWidget"
	BridgeService_GetWidgetInfo_FullMethodName         = "/bridge.BridgeService/GetWidgetInfo"
	BridgeService_GetAllWidgets_FullMethodName         = "/bridge.BridgeService/GetAllWidgets"
	BridgeService_SubscribeEvents_FullMethodName       = "/bridge.BridgeService/SubscribeEvents"
	BridgeService_Quit_FullMethodName                  = "/bridge.BridgeService/Quit"
)

// BridgeServiceClient is the client API for BridgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BridgeService provides high-performance binary protocol for Tsyne bridge
type BridgeServiceClient interface {
	// Window operations
	CreateWindow(ctx context.Context, in *CreateWindowRequest, opts ...grpc.CallOption) (*Response, error)
	ShowWindow(ctx context.Context, in *ShowWindowRequest, opts ...grpc.CallOption) (*Response, error)
	SetContent(ctx context.Context, in *SetContentRequest, opts ...grpc.CallOption) (*Response, error)
	ResizeWindow(ctx context.Context, in *ResizeWindowRequest, opts ...grpc.CallOption) (*Response, error)
	SetWindowTitle(ctx context.Context, in *SetWindowTitleRequest, opts ...grpc.CallOption) (*Response, error)
	CenterWindow(ctx context.Context, in *CenterWindowRequest, opts ...grpc.CallOption) (*Response, error)
	SetWindowFullScreen(ctx context.Context, in *SetWindowFullScreenRequest, opts ...grpc.CallOption) (*Response, error)
	// Widget creation
	CreateImage(ctx context.Context, in *CreateImageRequest, opts ...grpc.CallOption) (*Response, error)
	CreateLabel(ctx context.Context, in *CreateLabelRequest, opts ...grpc.CallOption) (*Response, error)
	CreateButton(ctx context.Context, in *CreateButtonRequest, opts ...grpc.CallOption) (*Response, error)
	CreateEntry(ctx context.Context, in *CreateEntryRequest, opts ...grpc.CallOption) (*Response, error)
	CreateVBox(ctx context.Context, in *CreateVBoxRequest, opts ...grpc.CallOption) (*Response, error)
	CreateHBox(ctx context.Context, in *CreateHBoxRequest, opts ...grpc.CallOption) (*Response, error)
	CreateCheckbox(ctx context.Context, in *CreateCheckboxRequest, opts ...grpc.CallOption) (*Response, error)
	CreateSelect(ctx context.Context, in *CreateSelectRequest, opts ...grpc.CallOption) (*Response, error)
	// Container creation
	CreateScroll(ctx context.Context, in *CreateScrollRequest, opts ...grpc.CallOption) (*Response, error)
	CreateGrid(ctx context.Context, in *CreateGridRequest, opts ...grpc.CallOption) (*Response, error)
	CreateCenter(ctx context.Context, in *CreateCenterRequest, opts ...grpc.CallOption) (*Response, error)
	CreateClip(ctx context.Context, in *CreateClipRequest, opts ...grpc.CallOption) (*Response, error)
	CreateMax(ctx context.Context, in *CreateMaxRequest, opts ...grpc.CallOption) (*Response, error)
	CreateStack(ctx context.Context, in *CreateStackRequest, opts ...grpc.CallOption) (*Response, error)
	CreateCard(ctx context.Context, in *CreateCardRequest, opts ...grpc.CallOption) (*Response, error)
	CreateAccordion(ctx context.Context, in *CreateAccordionRequest, opts ...grpc.CallOption) (*Response, error)
	CreateForm(ctx context.Context, in *CreateFormRequest, opts ...grpc.CallOption) (*Response, error)
	CreateBorder(ctx context.Context, in *CreateBorderRequest, opts ...grpc.CallOption) (*Response, error)
	CreateGridWrap(ctx context.Context, in *CreateGridWrapRequest, opts ...grpc.CallOption) (*Response, error)
	CreateAdaptiveGrid(ctx context.Context, in *CreateAdaptiveGridRequest, opts ...grpc.CallOption) (*Response, error)
	CreatePadded(ctx context.Context, in *CreatePaddedRequest, opts ...grpc.CallOption) (*Response, error)
	CreateSplit(ctx context.Context, in *CreateSplitRequest, opts ...grpc.CallOption) (*Response, error)
	CreateTabs(ctx context.Context, in *CreateTabsRequest, opts ...grpc.CallOption) (*Response, error)
	CreateDocTabs(ctx context.Context, in *CreateDocTabsRequest, opts ...grpc.CallOption) (*Response, error)
	CreateThemeOverride(ctx context.Context, in *CreateThemeOverrideRequest, opts ...grpc.CallOption) (*Response, error)
	CreateInnerWindow(ctx context.Context, in *CreateInnerWindowRequest, opts ...grpc.CallOption) (*Response, error)
	CreateNavigation(ctx context.Context, in *CreateNavigationRequest, opts ...grpc.CallOption) (*Response, error)
	CreatePopup(ctx context.Context, in *CreatePopupRequest, opts ...grpc.CallOption) (*Response, error)
	CreateMultipleWindows(ctx context.Context, in *CreateMultipleWindowsRequest, opts ...grpc.CallOption) (*Response, error)
	// Resources
	RegisterResource(ctx context.Context, in *RegisterResourceRequest, opts ...grpc.CallOption) (*Response, error)
	UnregisterResource(ctx context.Context, in *UnregisterResourceRequest, opts ...grpc.CallOption) (*Response, error)
	// Widget updates
	UpdateImage(ctx context.Context, in *UpdateImageRequest, opts ...grpc.CallOption) (*Response, error)
	SetText(ctx context.Context, in *SetTextRequest, opts ...grpc.CallOption) (*Response, error)
	GetText(ctx context.Context, in *GetTextRequest, opts ...grpc.CallOption) (*GetTextResponse, error)
	SetProgress(ctx context.Context, in *SetProgressRequest, opts ...grpc.CallOption) (*Response, error)
	GetProgress(ctx context.Context, in *GetProgressRequest, opts ...grpc.CallOption) (*GetProgressResponse, error)
	SetChecked(ctx context.Context, in *SetCheckedRequest, opts ...grpc.CallOption) (*Response, error)
	GetChecked(ctx context.Context, in *GetCheckedRequest, opts ...grpc.CallOption) (*GetCheckedResponse, error)
	// Interactions
	ClickWidget(ctx context.Context, in *ClickWidgetRequest, opts ...grpc.CallOption) (*Response, error)
	TypeText(ctx context.Context, in *TypeTextRequest, opts ...grpc.CallOption) (*Response, error)
	DoubleTapWidget(ctx context.Context, in *DoubleTapWidgetRequest, opts ...grpc.CallOption) (*Response, error)
	RightClickWidget(ctx context.Context, in *RightClickWidgetRequest, opts ...grpc.CallOption) (*Response, error)
	DragWidget(ctx context.Context, in *DragWidgetRequest, opts ...grpc.CallOption) (*Response, error)
	// Custom IDs
	RegisterCustomId(ctx context.Context, in *RegisterCustomIdRequest, opts ...grpc.CallOption) (*Response, error)
	// Queries
	FindWidget(ctx context.Context, in *FindWidgetRequest, opts ...grpc.CallOption) (*FindWidgetResponse, error)
	GetWidgetInfo(ctx context.Context, in *GetWidgetInfoRequest, opts ...grpc.CallOption) (*WidgetInfoResponse, error)
	GetAllWidgets(ctx context.Context, in *GetAllWidgetsRequest, opts ...grpc.CallOption) (*GetAllWidgetsResponse, error)
	// Events (streaming)
	SubscribeEvents(ctx context.Context, in *EventSubscription, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// Lifecycle
	Quit(ctx context.Context, in *QuitRequest, opts ...grpc.CallOption) (*Response, error)
}

type bridgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBridgeServiceClient(cc grpc.ClientConnInterface) BridgeServiceClient {
	return &bridgeServiceClient{cc}
}

func (c *bridgeServiceClient) CreateWindow(ctx context.Context, in *CreateWindowRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateWindow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) ShowWindow(ctx context.Context, in *ShowWindowRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_ShowWindow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) SetContent(ctx context.Context, in *SetContentRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_SetContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) ResizeWindow(ctx context.Context, in *ResizeWindowRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_ResizeWindow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) SetWindowTitle(ctx context.Context, in *SetWindowTitleRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_SetWindowTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CenterWindow(ctx context.Context, in *CenterWindowRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CenterWindow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) SetWindowFullScreen(ctx context.Context, in *SetWindowFullScreenRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_SetWindowFullScreen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateImage(ctx context.Context, in *CreateImageRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateLabel(ctx context.Context, in *CreateLabelRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateButton(ctx context.Context, in *CreateButtonRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateButton_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateEntry(ctx context.Context, in *CreateEntryRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateVBox(ctx context.Context, in *CreateVBoxRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateVBox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateHBox(ctx context.Context, in *CreateHBoxRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateHBox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateCheckbox(ctx context.Context, in *CreateCheckboxRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateCheckbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateSelect(ctx context.Context, in *CreateSelectRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateSelect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateScroll(ctx context.Context, in *CreateScrollRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateScroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateGrid(ctx context.Context, in *CreateGridRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateGrid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateCenter(ctx context.Context, in *CreateCenterRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateCenter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateClip(ctx context.Context, in *CreateClipRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateClip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateMax(ctx context.Context, in *CreateMaxRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateMax_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateStack(ctx context.Context, in *CreateStackRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateStack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateCard(ctx context.Context, in *CreateCardRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateAccordion(ctx context.Context, in *CreateAccordionRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateAccordion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateForm(ctx context.Context, in *CreateFormRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateForm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateBorder(ctx context.Context, in *CreateBorderRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateBorder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateGridWrap(ctx context.Context, in *CreateGridWrapRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateGridWrap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateAdaptiveGrid(ctx context.Context, in *CreateAdaptiveGridRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateAdaptiveGrid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreatePadded(ctx context.Context, in *CreatePaddedRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreatePadded_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateSplit(ctx context.Context, in *CreateSplitRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateSplit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateTabs(ctx context.Context, in *CreateTabsRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateTabs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateDocTabs(ctx context.Context, in *CreateDocTabsRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateDocTabs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateThemeOverride(ctx context.Context, in *CreateThemeOverrideRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateThemeOverride_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateInnerWindow(ctx context.Context, in *CreateInnerWindowRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateInnerWindow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateNavigation(ctx context.Context, in *CreateNavigationRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateNavigation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreatePopup(ctx context.Context, in *CreatePopupRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreatePopup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) CreateMultipleWindows(ctx context.Context, in *CreateMultipleWindowsRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_CreateMultipleWindows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) RegisterResource(ctx context.Context, in *RegisterResourceRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_RegisterResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) UnregisterResource(ctx context.Context, in *UnregisterResourceRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_UnregisterResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) UpdateImage(ctx context.Context, in *UpdateImageRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_UpdateImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) SetText(ctx context.Context, in *SetTextRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_SetText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) GetText(ctx context.Context, in *GetTextRequest, opts ...grpc.CallOption) (*GetTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTextResponse)
	err := c.cc.Invoke(ctx, BridgeService_GetText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) SetProgress(ctx context.Context, in *SetProgressRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_SetProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) GetProgress(ctx context.Context, in *GetProgressRequest, opts ...grpc.CallOption) (*GetProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProgressResponse)
	err := c.cc.Invoke(ctx, BridgeService_GetProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) SetChecked(ctx context.Context, in *SetCheckedRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_SetChecked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) GetChecked(ctx context.Context, in *GetCheckedRequest, opts ...grpc.CallOption) (*GetCheckedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCheckedResponse)
	err := c.cc.Invoke(ctx, BridgeService_GetChecked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) ClickWidget(ctx context.Context, in *ClickWidgetRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_ClickWidget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) TypeText(ctx context.Context, in *TypeTextRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_TypeText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) DoubleTapWidget(ctx context.Context, in *DoubleTapWidgetRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_DoubleTapWidget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) RightClickWidget(ctx context.Context, in *RightClickWidgetRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_RightClickWidget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) DragWidget(ctx context.Context, in *DragWidgetRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_DragWidget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) RegisterCustomId(ctx context.Context, in *RegisterCustomIdRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_RegisterCustomId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) FindWidget(ctx context.Context, in *FindWidgetRequest, opts ...grpc.CallOption) (*FindWidgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindWidgetResponse)
	err := c.cc.Invoke(ctx, BridgeService_FindWidget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) GetWidgetInfo(ctx context.Context, in *GetWidgetInfoRequest, opts ...grpc.CallOption) (*WidgetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WidgetInfoResponse)
	err := c.cc.Invoke(ctx, BridgeService_GetWidgetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) GetAllWidgets(ctx context.Context, in *GetAllWidgetsRequest, opts ...grpc.CallOption) (*GetAllWidgetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllWidgetsResponse)
	err := c.cc.Invoke(ctx, BridgeService_GetAllWidgets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeServiceClient) SubscribeEvents(ctx context.Context, in *EventSubscription, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BridgeService_ServiceDesc.Streams[0], BridgeService_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventSubscription, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BridgeService_SubscribeEventsClient = grpc.ServerStreamingClient[Event]

func (c *bridgeServiceClient) Quit(ctx context.Context, in *QuitRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, BridgeService_Quit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BridgeServiceServer is the server API for BridgeService service.
// All implementations must embed UnimplementedBridgeServiceServer
// for forward compatibility.
//
// BridgeService provides high-performance binary protocol for Tsyne bridge
type BridgeServiceServer interface {
	// Window operations
	CreateWindow(context.Context, *CreateWindowRequest) (*Response, error)
	ShowWindow(context.Context, *ShowWindowRequest) (*Response, error)
	SetContent(context.Context, *SetContentRequest) (*Response, error)
	ResizeWindow(context.Context, *ResizeWindowRequest) (*Response, error)
	SetWindowTitle(context.Context, *SetWindowTitleRequest) (*Response, error)
	CenterWindow(context.Context, *CenterWindowRequest) (*Response, error)
	SetWindowFullScreen(context.Context, *SetWindowFullScreenRequest) (*Response, error)
	// Widget creation
	CreateImage(context.Context, *CreateImageRequest) (*Response, error)
	CreateLabel(context.Context, *CreateLabelRequest) (*Response, error)
	CreateButton(context.Context, *CreateButtonRequest) (*Response, error)
	CreateEntry(context.Context, *CreateEntryRequest) (*Response, error)
	CreateVBox(context.Context, *CreateVBoxRequest) (*Response, error)
	CreateHBox(context.Context, *CreateHBoxRequest) (*Response, error)
	CreateCheckbox(context.Context, *CreateCheckboxRequest) (*Response, error)
	CreateSelect(context.Context, *CreateSelectRequest) (*Response, error)
	// Container creation
	CreateScroll(context.Context, *CreateScrollRequest) (*Response, error)
	CreateGrid(context.Context, *CreateGridRequest) (*Response, error)
	CreateCenter(context.Context, *CreateCenterRequest) (*Response, error)
	CreateClip(context.Context, *CreateClipRequest) (*Response, error)
	CreateMax(context.Context, *CreateMaxRequest) (*Response, error)
	CreateStack(context.Context, *CreateStackRequest) (*Response, error)
	CreateCard(context.Context, *CreateCardRequest) (*Response, error)
	CreateAccordion(context.Context, *CreateAccordionRequest) (*Response, error)
	CreateForm(context.Context, *CreateFormRequest) (*Response, error)
	CreateBorder(context.Context, *CreateBorderRequest) (*Response, error)
	CreateGridWrap(context.Context, *CreateGridWrapRequest) (*Response, error)
	CreateAdaptiveGrid(context.Context, *CreateAdaptiveGridRequest) (*Response, error)
	CreatePadded(context.Context, *CreatePaddedRequest) (*Response, error)
	CreateSplit(context.Context, *CreateSplitRequest) (*Response, error)
	CreateTabs(context.Context, *CreateTabsRequest) (*Response, error)
	CreateDocTabs(context.Context, *CreateDocTabsRequest) (*Response, error)
	CreateThemeOverride(context.Context, *CreateThemeOverrideRequest) (*Response, error)
	CreateInnerWindow(context.Context, *CreateInnerWindowRequest) (*Response, error)
	CreateNavigation(context.Context, *CreateNavigationRequest) (*Response, error)
	CreatePopup(context.Context, *CreatePopupRequest) (*Response, error)
	CreateMultipleWindows(context.Context, *CreateMultipleWindowsRequest) (*Response, error)
	// Resources
	RegisterResource(context.Context, *RegisterResourceRequest) (*Response, error)
	UnregisterResource(context.Context, *UnregisterResourceRequest) (*Response, error)
	// Widget updates
	UpdateImage(context.Context, *UpdateImageRequest) (*Response, error)
	SetText(context.Context, *SetTextRequest) (*Response, error)
	GetText(context.Context, *GetTextRequest) (*GetTextResponse, error)
	SetProgress(context.Context, *SetProgressRequest) (*Response, error)
	GetProgress(context.Context, *GetProgressRequest) (*GetProgressResponse, error)
	SetChecked(context.Context, *SetCheckedRequest) (*Response, error)
	GetChecked(context.Context, *GetCheckedRequest) (*GetCheckedResponse, error)
	// Interactions
	ClickWidget(context.Context, *ClickWidgetRequest) (*Response, error)
	TypeText(context.Context, *TypeTextRequest) (*Response, error)
	DoubleTapWidget(context.Context, *DoubleTapWidgetRequest) (*Response, error)
	RightClickWidget(context.Context, *RightClickWidgetRequest) (*Response, error)
	DragWidget(context.Context, *DragWidgetRequest) (*Response, error)
	// Custom IDs
	RegisterCustomId(context.Context, *RegisterCustomIdRequest) (*Response, error)
	// Queries
	FindWidget(context.Context, *FindWidgetRequest) (*FindWidgetResponse, error)
	GetWidgetInfo(context.Context, *GetWidgetInfoRequest) (*WidgetInfoResponse, error)
	GetAllWidgets(context.Context, *GetAllWidgetsRequest) (*GetAllWidgetsResponse, error)
	// Events (streaming)
	SubscribeEvents(*EventSubscription, grpc.ServerStreamingServer[Event]) error
	// Lifecycle
	Quit(context.Context, *QuitRequest) (*Response, error)
	mustEmbedUnimplementedBridgeServiceServer()
}

// UnimplementedBridgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBridgeServiceServer struct{}

func (UnimplementedBridgeServiceServer) CreateWindow(context.Context, *CreateWindowRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWindow not implemented")
}
func (UnimplementedBridgeServiceServer) ShowWindow(context.Context, *ShowWindowRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ShowWindow not implemented")
}
func (UnimplementedBridgeServiceServer) SetContent(context.Context, *SetContentRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetContent not implemented")
}
func (UnimplementedBridgeServiceServer) ResizeWindow(context.Context, *ResizeWindowRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ResizeWindow not implemented")
}
func (UnimplementedBridgeServiceServer) SetWindowTitle(context.Context, *SetWindowTitleRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetWindowTitle not implemented")
}
func (UnimplementedBridgeServiceServer) CenterWindow(context.Context, *CenterWindowRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CenterWindow not implemented")
}
func (UnimplementedBridgeServiceServer) SetWindowFullScreen(context.Context, *SetWindowFullScreenRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetWindowFullScreen not implemented")
}
func (UnimplementedBridgeServiceServer) CreateImage(context.Context, *CreateImageRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateImage not implemented")
}
func (UnimplementedBridgeServiceServer) CreateLabel(context.Context, *CreateLabelRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLabel not implemented")
}
func (UnimplementedBridgeServiceServer) CreateButton(context.Context, *CreateButtonRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateButton not implemented")
}
func (UnimplementedBridgeServiceServer) CreateEntry(context.Context, *CreateEntryRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEntry not implemented")
}
func (UnimplementedBridgeServiceServer) CreateVBox(context.Context, *CreateVBoxRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVBox not implemented")
}
func (UnimplementedBridgeServiceServer) CreateHBox(context.Context, *CreateHBoxRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateHBox not implemented")
}
func (UnimplementedBridgeServiceServer) CreateCheckbox(context.Context, *CreateCheckboxRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCheckbox not implemented")
}
func (UnimplementedBridgeServiceServer) CreateSelect(context.Context, *CreateSelectRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSelect not implemented")
}
func (UnimplementedBridgeServiceServer) CreateScroll(context.Context, *CreateScrollRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateScroll not implemented")
}
func (UnimplementedBridgeServiceServer) CreateGrid(context.Context, *CreateGridRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGrid not implemented")
}
func (UnimplementedBridgeServiceServer) CreateCenter(context.Context, *CreateCenterRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCenter not implemented")
}
func (UnimplementedBridgeServiceServer) CreateClip(context.Context, *CreateClipRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateClip not implemented")
}
func (UnimplementedBridgeServiceServer) CreateMax(context.Context, *CreateMaxRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMax not implemented")
}
func (UnimplementedBridgeServiceServer) CreateStack(context.Context, *CreateStackRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStack not implemented")
}
func (UnimplementedBridgeServiceServer) CreateCard(context.Context, *CreateCardRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCard not implemented")
}
func (UnimplementedBridgeServiceServer) CreateAccordion(context.Context, *CreateAccordionRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAccordion not implemented")
}
func (UnimplementedBridgeServiceServer) CreateForm(context.Context, *CreateFormRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateForm not implemented")
}
func (UnimplementedBridgeServiceServer) CreateBorder(context.Context, *CreateBorderRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBorder not implemented")
}
func (UnimplementedBridgeServiceServer) CreateGridWrap(context.Context, *CreateGridWrapRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGridWrap not implemented")
}
func (UnimplementedBridgeServiceServer) CreateAdaptiveGrid(context.Context, *CreateAdaptiveGridRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAdaptiveGrid not implemented")
}
func (UnimplementedBridgeServiceServer) CreatePadded(context.Context, *CreatePaddedRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePadded not implemented")
}
func (UnimplementedBridgeServiceServer) CreateSplit(context.Context, *CreateSplitRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSplit not implemented")
}
func (UnimplementedBridgeServiceServer) CreateTabs(context.Context, *CreateTabsRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTabs not implemented")
}
func (UnimplementedBridgeServiceServer) CreateDocTabs(context.Context, *CreateDocTabsRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDocTabs not implemented")
}
func (UnimplementedBridgeServiceServer) CreateThemeOverride(context.Context, *CreateThemeOverrideRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateThemeOverride not implemented")
}
func (UnimplementedBridgeServiceServer) CreateInnerWindow(context.Context, *CreateInnerWindowRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInnerWindow not implemented")
}
func (UnimplementedBridgeServiceServer) CreateNavigation(context.Context, *CreateNavigationRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNavigation not implemented")
}
func (UnimplementedBridgeServiceServer) CreatePopup(context.Context, *CreatePopupRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePopup not implemented")
}
func (UnimplementedBridgeServiceServer) CreateMultipleWindows(context.Context, *CreateMultipleWindowsRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMultipleWindows not implemented")
}
func (UnimplementedBridgeServiceServer) RegisterResource(context.Context, *RegisterResourceRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterResource not implemented")
}
func (UnimplementedBridgeServiceServer) UnregisterResource(context.Context, *UnregisterResourceRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterResource not implemented")
}
func (UnimplementedBridgeServiceServer) UpdateImage(context.Context, *UpdateImageRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateImage not implemented")
}
func (UnimplementedBridgeServiceServer) SetText(context.Context, *SetTextRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetText not implemented")
}
func (UnimplementedBridgeServiceServer) GetText(context.Context, *GetTextRequest) (*GetTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetText not implemented")
}
func (UnimplementedBridgeServiceServer) SetProgress(context.Context, *SetProgressRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetProgress not implemented")
}
func (UnimplementedBridgeServiceServer) GetProgress(context.Context, *GetProgressRequest) (*GetProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProgress not implemented")
}
func (UnimplementedBridgeServiceServer) SetChecked(context.Context, *SetCheckedRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetChecked not implemented")
}
func (UnimplementedBridgeServiceServer) GetChecked(context.Context, *GetCheckedRequest) (*GetCheckedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChecked not implemented")
}
func (UnimplementedBridgeServiceServer) ClickWidget(context.Context, *ClickWidgetRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ClickWidget not implemented")
}
func (UnimplementedBridgeServiceServer) TypeText(context.Context, *TypeTextRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method TypeText not implemented")
}
func (UnimplementedBridgeServiceServer) DoubleTapWidget(context.Context, *DoubleTapWidgetRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method DoubleTapWidget not implemented")
}
func (UnimplementedBridgeServiceServer) RightClickWidget(context.Context, *RightClickWidgetRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RightClickWidget not implemented")
}
func (UnimplementedBridgeServiceServer) DragWidget(context.Context, *DragWidgetRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method DragWidget not implemented")
}
func (UnimplementedBridgeServiceServer) RegisterCustomId(context.Context, *RegisterCustomIdRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterCustomId not implemented")
}
func (UnimplementedBridgeServiceServer) FindWidget(context.Context, *FindWidgetRequest) (*FindWidgetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindWidget not implemented")
}
func (UnimplementedBridgeServiceServer) GetWidgetInfo(context.Context, *GetWidgetInfoRequest) (*WidgetInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWidgetInfo not implemented")
}
func (UnimplementedBridgeServiceServer) GetAllWidgets(context.Context, *GetAllWidgetsRequest) (*GetAllWidgetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllWidgets not implemented")
}
func (UnimplementedBridgeServiceServer) SubscribeEvents(*EventSubscription, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedBridgeServiceServer) Quit(context.Context, *QuitRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Quit not implemented")
}
func (UnimplementedBridgeServiceServer) mustEmbedUnimplementedBridgeServiceServer() {}
func (UnimplementedBridgeServiceServer) testEmbeddedByValue()                       {}

// UnsafeBridgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BridgeServiceServer will
// result in compilation errors.
type UnsafeBridgeServiceServer interface {
	mustEmbedUnimplementedBridgeServiceServer()
}

func RegisterBridgeServiceServer(s grpc.ServiceRegistrar, srv BridgeServiceServer) {
	// If the following call panics, it indicates UnimplementedBridgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BridgeService_ServiceDesc, srv)
}

func _BridgeService_CreateWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateWindow(ctx, req.(*CreateWindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_ShowWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowWindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).ShowWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_ShowWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).ShowWindow(ctx, req.(*ShowWindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_SetContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).SetContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_SetContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).SetContent(ctx, req.(*SetContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_ResizeWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeWindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).ResizeWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_ResizeWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).ResizeWindow(ctx, req.(*ResizeWindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_SetWindowTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetWindowTitleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).SetWindowTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_SetWindowTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).SetWindowTitle(ctx, req.(*SetWindowTitleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CenterWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CenterWindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CenterWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CenterWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CenterWindow(ctx, req.(*CenterWindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_SetWindowFullScreen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetWindowFullScreenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).SetWindowFullScreen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_SetWindowFullScreen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).SetWindowFullScreen(ctx, req.(*SetWindowFullScreenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateImage(ctx, req.(*CreateImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateLabel(ctx, req.(*CreateLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateButton_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateButtonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateButton(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateButton_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateButton(ctx, req.(*CreateButtonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateEntry(ctx, req.(*CreateEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateVBox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVBoxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateVBox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateVBox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateVBox(ctx, req.(*CreateVBoxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateHBox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHBoxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateHBox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateHBox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateHBox(ctx, req.(*CreateHBoxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateCheckbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCheckboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateCheckbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateCheckbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateCheckbox(ctx, req.(*CreateCheckboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateSelect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSelectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateSelect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateSelect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateSelect(ctx, req.(*CreateSelectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateScroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateScroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateScroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateScroll(ctx, req.(*CreateScrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateGrid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGridRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateGrid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateGrid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateGrid(ctx, req.(*CreateGridRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateCenter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCenterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateCenter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateCenter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateCenter(ctx, req.(*CreateCenterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateClip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateClip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateClip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateClip(ctx, req.(*CreateClipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateMax_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMaxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateMax(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateMax_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateMax(ctx, req.(*CreateMaxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateStack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateStack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateStack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateStack(ctx, req.(*CreateStackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateCard(ctx, req.(*CreateCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateAccordion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccordionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateAccordion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateAccordion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateAccordion(ctx, req.(*CreateAccordionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateForm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFormRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateForm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateForm(ctx, req.(*CreateFormRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateBorder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBorderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateBorder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateBorder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateBorder(ctx, req.(*CreateBorderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateGridWrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGridWrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateGridWrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateGridWrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateGridWrap(ctx, req.(*CreateGridWrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateAdaptiveGrid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdaptiveGridRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateAdaptiveGrid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateAdaptiveGrid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateAdaptiveGrid(ctx, req.(*CreateAdaptiveGridRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreatePadded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaddedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreatePadded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreatePadded_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreatePadded(ctx, req.(*CreatePaddedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateSplit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSplitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateSplit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateSplit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateSplit(ctx, req.(*CreateSplitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateTabs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTabsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateTabs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateTabs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateTabs(ctx, req.(*CreateTabsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateDocTabs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDocTabsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateDocTabs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateDocTabs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateDocTabs(ctx, req.(*CreateDocTabsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateThemeOverride_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateThemeOverrideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateThemeOverride(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateThemeOverride_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateThemeOverride(ctx, req.(*CreateThemeOverrideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateInnerWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInnerWindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateInnerWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateInnerWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateInnerWindow(ctx, req.(*CreateInnerWindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateNavigation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNavigationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateNavigation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateNavigation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateNavigation(ctx, req.(*CreateNavigationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreatePopup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePopupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreatePopup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreatePopup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreatePopup(ctx, req.(*CreatePopupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_CreateMultipleWindows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMultipleWindowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).CreateMultipleWindows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_CreateMultipleWindows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).CreateMultipleWindows(ctx, req.(*CreateMultipleWindowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_RegisterResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).RegisterResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_RegisterResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).RegisterResource(ctx, req.(*RegisterResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_UnregisterResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).UnregisterResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_UnregisterResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).UnregisterResource(ctx, req.(*UnregisterResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_UpdateImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).UpdateImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_UpdateImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).UpdateImage(ctx, req.(*UpdateImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_SetText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).SetText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_SetText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).SetText(ctx, req.(*SetTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_GetText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).GetText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_GetText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).GetText(ctx, req.(*GetTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_SetProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).SetProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_SetProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).SetProgress(ctx, req.(*SetProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_GetProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).GetProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_GetProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).GetProgress(ctx, req.(*GetProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_SetChecked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCheckedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).SetChecked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_SetChecked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).SetChecked(ctx, req.(*SetCheckedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_GetChecked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).GetChecked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_GetChecked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).GetChecked(ctx, req.(*GetCheckedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_ClickWidget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClickWidgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).ClickWidget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_ClickWidget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).ClickWidget(ctx, req.(*ClickWidgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_TypeText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TypeTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).TypeText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_TypeText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).TypeText(ctx, req.(*TypeTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_DoubleTapWidget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoubleTapWidgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).DoubleTapWidget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_DoubleTapWidget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).DoubleTapWidget(ctx, req.(*DoubleTapWidgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_RightClickWidget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RightClickWidgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).RightClickWidget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_RightClickWidget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).RightClickWidget(ctx, req.(*RightClickWidgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_DragWidget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DragWidgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).DragWidget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_DragWidget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).DragWidget(ctx, req.(*DragWidgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_RegisterCustomId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCustomIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).RegisterCustomId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_RegisterCustomId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).RegisterCustomId(ctx, req.(*RegisterCustomIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_FindWidget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindWidgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).FindWidget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_FindWidget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).FindWidget(ctx, req.(*FindWidgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_GetWidgetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWidgetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).GetWidgetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_GetWidgetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).GetWidgetInfo(ctx, req.(*GetWidgetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_GetAllWidgets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllWidgetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).GetAllWidgets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_GetAllWidgets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).GetAllWidgets(ctx, req.(*GetAllWidgetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BridgeService_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventSubscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BridgeServiceServer).SubscribeEvents(m, &grpc.GenericServerStream[EventSubscription, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BridgeService_SubscribeEventsServer = grpc.ServerStreamingServer[Event]

func _BridgeService_Quit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServiceServer).Quit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BridgeService_Quit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServiceServer).Quit(ctx, req.(*QuitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BridgeService_ServiceDesc is the grpc.ServiceDesc for BridgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BridgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bridge.BridgeService",
	HandlerType: (*BridgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWindow",
			Handler:    _BridgeService_CreateWindow_Handler,
		},
		{
			MethodName: "ShowWindow",
			Handler:    _BridgeService_ShowWindow_Handler,
		},
		{
			MethodName: "SetContent",
			Handler:    _BridgeService_SetContent_Handler,
		},
		{
			MethodName: "ResizeWindow",
			Handler:    _BridgeService_ResizeWindow_Handler,
		},
		{
			MethodName: "SetWindowTitle",
			Handler:    _BridgeService_SetWindowTitle_Handler,
		},
		{
			MethodName: "CenterWindow",
			Handler:    _BridgeService_CenterWindow_Handler,
		},
		{
			MethodName: "SetWindowFullScreen",
			Handler:    _BridgeService_SetWindowFullScreen_Handler,
		},
		{
			MethodName: "CreateImage",
			Handler:    _BridgeService_CreateImage_Handler,
		},
		{
			MethodName: "CreateLabel",
			Handler:    _BridgeService_CreateLabel_Handler,
		},
		{
			MethodName: "CreateButton",
			Handler:    _BridgeService_CreateButton_Handler,
		},
		{
			MethodName: "CreateEntry",
			Handler:    _BridgeService_CreateEntry_Handler,
		},
		{
			MethodName: "CreateVBox",
			Handler:    _BridgeService_CreateVBox_Handler,
		},
		{
			MethodName: "CreateHBox",
			Handler:    _BridgeService_CreateHBox_Handler,
		},
		{
			MethodName: "CreateCheckbox",
			Handler:    _BridgeService_CreateCheckbox_Handler,
		},
		{
			MethodName: "CreateSelect",
			Handler:    _BridgeService_CreateSelect_Handler,
		},
		{
			MethodName: "CreateScroll",
			Handler:    _BridgeService_CreateScroll_Handler,
		},
		{
			MethodName: "CreateGrid",
			Handler:    _BridgeService_CreateGrid_Handler,
		},
		{
			MethodName: "CreateCenter",
			Handler:    _BridgeService_CreateCenter_Handler,
		},
		{
			MethodName: "CreateClip",
			Handler:    _BridgeService_CreateClip_Handler,
		},
		{
			MethodName: "CreateMax",
			Handler:    _BridgeService_CreateMax_Handler,
		},
		{
			MethodName: "CreateStack",
			Handler:    _BridgeService_CreateStack_Handler,
		},
		{
			MethodName: "CreateCard",
			Handler:    _BridgeService_CreateCard_Handler,
		},
		{
			MethodName: "CreateAccordion",
			Handler:    _BridgeService_CreateAccordion_Handler,
		},
		{
			MethodName: "CreateForm",
			Handler:    _BridgeService_CreateForm_Handler,
		},
		{
			MethodName: "CreateBorder",
			Handler:    _BridgeService_CreateBorder_Handler,
		},
		{
			MethodName: "CreateGridWrap",
			Handler:    _BridgeService_CreateGridWrap_Handler,
		},
		{
			MethodName: "CreateAdaptiveGrid",
			Handler:    _BridgeService_CreateAdaptiveGrid_Handler,
		},
		{
			MethodName: "CreatePadded",
			Handler:    _BridgeService_CreatePadded_Handler,
		},
		{
			MethodName: "CreateSplit",
			Handler:    _BridgeService_CreateSplit_Handler,
		},
		{
			MethodName: "CreateTabs",
			Handler:    _BridgeService_CreateTabs_Handler,
		},
		{
			MethodName: "CreateDocTabs",
			Handler:    _BridgeService_CreateDocTabs_Handler,
		},
		{
			MethodName: "CreateThemeOverride",
			Handler:    _BridgeService_CreateThemeOverride_Handler,
		},
		{
			MethodName: "CreateInnerWindow",
			Handler:    _BridgeService_CreateInnerWindow_Handler,
		},
		{
			MethodName: "CreateNavigation",
			Handler:    _BridgeService_CreateNavigation_Handler,
		},
		{
			MethodName: "CreatePopup",
			Handler:    _BridgeService_CreatePopup_Handler,
		},
		{
			MethodName: "CreateMultipleWindows",
			Handler:    _BridgeService_CreateMultipleWindows_Handler,
		},
		{
			MethodName: "RegisterResource",
			Handler:    _BridgeService_RegisterResource_Handler,
		},
		{
			MethodName: "UnregisterResource",
			Handler:    _BridgeService_UnregisterResource_Handler,
		},
		{
			MethodName: "UpdateImage",
			Handler:    _BridgeService_UpdateImage_Handler,
		},
		{
			MethodName: "SetText",
			Handler:    _BridgeService_SetText_Handler,
		},
		{
			MethodName: "GetText",
			Handler:    _BridgeService_GetText_Handler,
		},
		{
			MethodName: "SetProgress",
			Handler:    _BridgeService_SetProgress_Handler,
		},
		{
			MethodName: "GetProgress",
			Handler:    _BridgeService_GetProgress_Handler,
		},
		{
			MethodName: "SetChecked",
			Handler:    _BridgeService_SetChecked_Handler,
		},
		{
			MethodName: "GetChecked",
			Handler:    _BridgeService_GetChecked_Handler,
		},
		{
			MethodName: "ClickWidget",
			Handler:    _BridgeService_ClickWidget_Handler,
		},
		{
			MethodName: "TypeText",
			Handler:    _BridgeService_TypeText_Handler,
		},
		{
			MethodName: "DoubleTapWidget",
			Handler:    _BridgeService_DoubleTapWidget_Handler,
		},
		{
			MethodName: "RightClickWidget",
			Handler:    _BridgeService_RightClickWidget_Handler,
		},
		{
			MethodName: "DragWidget",
			Handler:    _BridgeService_DragWidget_Handler,
		},
		{
			MethodName: "RegisterCustomId",
			Handler:    _BridgeService_RegisterCustomId_Handler,
		},
		{
			MethodName: "FindWidget",
			Handler:    _BridgeService_FindWidget_Handler,
		},
		{
			MethodName: "GetWidgetInfo",
			Handler:    _BridgeService_GetWidgetInfo_Handler,
		},
		{
			MethodName: "GetAllWidgets",
			Handler:    _BridgeService_GetAllWidgets_Handler,
		},
		{
			MethodName: "Quit",
			Handler:    _BridgeService_Quit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _BridgeService_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/bridge.proto",
}
